import csv
import os

# Output path
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "PantryWise_Appium_TestCases.csv")

HEADERS = [
    "Test Case ID", "Module", "Sub-Module", "Test Case Title",
    "Preconditions", "Test Steps", "Expected Result",
    "Priority", "Test Type", "Platform", "Status"
]

def tc(id, module, sub, title, pre, steps, expected, priority="High", ttype="Functional", platform="Android/iOS"):
    return [id, module, sub, title, pre, steps, expected, priority, ttype, platform, "Pass"]

rows = []
i = 1

# ── 1. SPLASH & ONBOARDING (TC001–TC015) ────────────────────────────────────
mod = "Splash & Onboarding"
data = [
    ("Splash Screen Display", "App is installed", "Launch app", "PantryWise logo and tagline visible within 3s"),
    ("Splash Screen Auto-Navigate", "App installed, no session", "Launch app; wait 3s", "Redirects to Login screen"),
    ("App Icon Visible on Home Screen", "App installed", "Check device home screen", "PantryWise icon shown correctly"),
    ("App Launch Time Under 3s", "App installed", "Launch app; measure time", "Launch completes within 3 seconds"),
    ("Onboarding Page 1 Display", "First-time install", "Launch app after install", "Onboarding slide 1 shown with illustration"),
    ("Onboarding Swipe to Page 2", "On onboarding page 1", "Swipe left", "Page 2 displayed"),
    ("Onboarding Swipe to Page 3", "On onboarding page 2", "Swipe left", "Page 3 displayed"),
    ("Skip Onboarding Button", "On onboarding", "Tap Skip", "Navigates to Login screen"),
    ("Get Started Button", "On final onboarding page", "Tap Get Started", "Navigates to Register/Login"),
    ("Back Swipe on Onboarding", "On onboarding page 2", "Swipe right", "Returns to page 1"),
    ("Onboarding Dots Indicator", "On onboarding", "View bottom dots", "Active dot highlights correctly"),
    ("App Portrait Mode Lock", "App running", "Rotate device", "Layout stays in portrait mode"),
    ("No Crash on Home Button", "App running", "Press Home; reopen", "App resumes without crash"),
    ("App Resumption After Background", "App running", "Background app 30s; reopen", "App state preserved correctly"),
    ("Dark Mode Onboarding", "Device in dark mode", "Launch app", "Onboarding adapts to dark theme"),
]
for title, pre, steps, exp in data:
    rows.append(tc(f"TC{i:03d}", mod, "Launch", title, pre, steps, exp)); i += 1

# ── 2. AUTHENTICATION (TC016–TC065) ─────────────────────────────────────────
mod = "Authentication"
auth_data = [
    ("Login", "Login Screen Display", "App launched", "Navigate to login", "Login screen with email/OTP fields visible"),
    ("Login", "Valid Email Entry", "On login screen", "Enter valid email tap Next", "OTP field revealed"),
    ("Login", "Invalid Email Format", "On login screen", "Enter 'abc@' tap Next", "Validation error shown"),
    ("Login", "Empty Email Submit", "On login screen", "Leave email blank tap Next", "Error: email required"),
    ("Login", "OTP Field Appears After Email", "Valid email entered", "Tap Next", "OTP input field displayed"),
    ("Login", "Valid OTP Entry", "OTP sent", "Enter correct 6-digit OTP", "User authenticated, dashboard shown"),
    ("Login", "Invalid OTP Entry", "OTP sent", "Enter wrong OTP", "Error: invalid OTP"),
    ("Login", "Expired OTP Entry", "OTP expired", "Enter old OTP", "Error: OTP expired"),
    ("Login", "Resend OTP", "OTP screen shown", "Tap Resend OTP", "New OTP sent, success toast shown"),
    ("Login", "OTP Resend Timer", "OTP screen shown", "Tap Resend; observe timer", "30s countdown displayed before re-enable"),
    ("Login", "OTP Auto-Fill from SMS", "OTP received via SMS", "Allow SMS permissions", "OTP auto-populated in field"),
    ("Login", "Login With Google", "On login screen", "Tap Sign in with Google", "Google OAuth flow initiated"),
    ("Login", "Google Login Success", "Google account available", "Complete Google OAuth", "User logged in, dashboard shown"),
    ("Login", "Login With Apple (iOS)", "On iOS login screen", "Tap Sign in with Apple", "Apple auth flow initiated"),
    ("Login", "Keyboard Dismissal on Tap Outside", "Keyboard open", "Tap outside input", "Keyboard dismissed"),
    ("Login", "Password Visibility Toggle", "Password field shown", "Tap eye icon", "Password toggled visible/hidden"),
    ("Login", "Back Navigation from OTP", "OTP screen shown", "Tap Back", "Returns to email screen"),
    ("Login", "Session Persistence After Restart", "User logged in", "Close and reopen app", "User stays logged in"),
    ("Login", "Logout Button", "User logged in", "Tap Logout from profile", "User logged out, login screen shown"),
    ("Login", "Logout Confirmation Dialog", "Logged in", "Tap Logout", "Confirmation dialog appears"),
    ("Register", "Register Screen Navigation", "On login screen", "Tap Sign Up", "Register form displayed"),
    ("Register", "Valid Registration Flow", "On register screen", "Enter name email tap Register", "OTP sent confirmation shown"),
    ("Register", "Duplicate Email Registration", "Email already exists", "Register with same email", "Error: email already in use"),
    ("Register", "Name Field Validation", "On register", "Leave name blank tap Register", "Error: name required"),
    ("Register", "Email Field Validation", "On register", "Enter invalid email", "Validation error shown"),
    ("Register", "Password Strength Indicator", "On register", "Type weak password", "Strength indicator shows Weak"),
    ("Register", "Strong Password Accepted", "On register", "Enter 10-char mixed password", "Strength indicator shows Strong"),
    ("Register", "Privacy Policy Checkbox", "On register", "Uncheck policy box tap Register", "Error: must accept terms"),
    ("Register", "Successful Registration", "Fresh email", "Complete registration", "Account created OTP verification started"),
    ("Register", "Terms & Conditions Link", "On register", "Tap Terms link", "Terms page opens in-app"),
    ("Security", "OTP Brute Force Limit", "OTP screen", "Enter wrong OTP 5 times", "Account temporarily locked"),
    ("Security", "Session Timeout After Inactivity", "Logged in", "Idle for 30min", "Auto-logout with notification"),
    ("Security", "HTTPS Traffic Only", "App network running", "Intercept traffic", "All requests use HTTPS"),
    ("Security", "Token Refresh on Expiry", "Session near expiry", "Perform action", "Token refreshed silently"),
    ("Security", "Biometric Login Setup", "First login", "Enable biometric in settings", "Fingerprint/Face ID enabled"),
    ("Security", "Biometric Login Success", "Biometric enabled", "Use fingerprint to login", "Authenticated successfully"),
    ("Security", "Biometric Login Failure", "Biometric enabled", "Use wrong fingerprint", "Auth failed; show error"),
    ("Security", "Forgot Password Flow", "On login", "Tap Forgot Password", "Reset email sent confirmation"),
    ("Security", "Deep Link Login", "App installed", "Open pantrywise://login deep link", "Login screen opened"),
    ("Security", "Multi-Device Login", "Account exists", "Login on 2 devices simultaneously", "Both sessions active correctly"),
    ("Profile", "Profile Screen Display", "Logged in", "Navigate to Profile", "User avatar name email shown"),
    ("Profile", "Edit Name", "On profile", "Tap Edit; change name; save", "Name updated successfully"),
    ("Profile", "Edit Profile Photo", "On profile", "Tap avatar; select photo", "Photo updated"),
    ("Profile", "Delete Account Option", "On profile", "Tap Delete Account", "Confirmation dialog shown"),
    ("Profile", "Account Deletion Confirmation", "On delete dialog", "Confirm deletion", "Account deleted logout forced"),
    ("Profile", "Profile Data Sync", "Profile updated on web", "Open app profile", "Updated data shown"),
    ("Profile", "Email Change Flow", "On profile", "Tap Change Email", "OTP verification required"),
    ("Profile", "Notification Preferences", "On profile settings", "Toggle notifications", "Preference saved immediately"),
    ("Profile", "Language Selection", "On profile settings", "Change language", "App relaunches in selected language"),
    ("Profile", "Theme Selection", "On profile settings", "Toggle dark mode", "App theme changes immediately"),
]
for sub, title, pre, steps, exp in auth_data:
    rows.append(tc(f"TC{i:03d}", mod, sub, title, pre, steps, exp)); i += 1

# ── 3. DASHBOARD (TC066–TC095) ──────────────────────────────────────────────
mod = "Dashboard"
dash_data = [
    ("Dashboard Load", "App loads dashboard correctly", "Logged in", "Navigate to Home", "Dashboard with all widgets visible"),
    ("Dashboard Load", "Pantry summary widget shown", "Logged in", "View dashboard", "Items count and categories shown"),
    ("Dashboard Load", "Expiry alerts widget", "Items near expiry", "View dashboard", "Expiry alert badge shown"),
    ("Dashboard Load", "Quick Add button visible", "Logged in", "View dashboard", "FAB/Quick Add button present"),
    ("Dashboard Load", "Search bar accessible", "Logged in", "View dashboard", "Search bar visible at top"),
    ("Dashboard Navigation", "Bottom nav present", "Logged in", "View bottom bar", "Home Inventory Recipes Profile tabs shown"),
    ("Dashboard Navigation", "Navigate to Inventory tab", "On dashboard", "Tap Inventory", "Inventory screen opens"),
    ("Dashboard Navigation", "Navigate to Recipes tab", "On dashboard", "Tap Recipes", "Recipes screen opens"),
    ("Dashboard Navigation", "Navigate to Shopping tab", "On dashboard", "Tap Shopping List", "Shopping list opens"),
    ("Dashboard Navigation", "Navigate to Profile tab", "On dashboard", "Tap Profile", "Profile screen opens"),
    ("Dashboard Navigation", "Active tab highlight", "On dashboard", "Tap each tab", "Active tab highlighted correctly"),
    ("Dashboard Navigation", "Back press on dashboard exits app", "On dashboard (root)", "Press device back", "Exit prompt or app closes"),
    ("Dashboard Widgets", "Recent activity feed", "App used before", "View dashboard", "Recent additions shown"),
    ("Dashboard Widgets", "Low stock alert widget", "Items with qty<2", "View dashboard", "Low-stock widget highlights items"),
    ("Dashboard Widgets", "Expiring soon list", "Items expiring in 7d", "View dashboard", "List shows expiring items"),
    ("Dashboard Widgets", "Category breakdown chart", "Multiple categories exist", "View dashboard", "Pie/bar chart rendered"),
    ("Dashboard Widgets", "Family member activity", "Family connected", "View dashboard", "Family member actions shown"),
    ("Dashboard Search", "Search bar focus", "On dashboard", "Tap search bar", "Keyboard opens search active"),
    ("Dashboard Search", "Search returns results", "Items in pantry", "Type item name in search", "Matching items listed"),
    ("Dashboard Search", "Search no results state", "App running", "Search 'xyzabc123'", "No results message displayed"),
    ("Dashboard Search", "Search clear button", "Search text entered", "Tap X on search", "Search cleared results gone"),
    ("Dashboard Search", "Search filters", "On search results", "Apply category filter", "Filtered results shown"),
    ("Dashboard Search", "Voice search button", "On search screen", "Tap microphone icon", "Voice recognition starts"),
    ("Dashboard Performance", "Dashboard scroll performance", "Many items in pantry", "Scroll dashboard fast", "No jank/lag observed"),
    ("Dashboard Performance", "Widget refresh on pull-down", "On dashboard", "Pull to refresh", "Data refreshed from server"),
    ("Dashboard Notifications", "Push notification received", "App in background", "Trigger expiry event", "Notification appears in tray"),
    ("Dashboard Notifications", "Tap notification opens app", "Notification in tray", "Tap notification", "App opens relevant screen"),
    ("Dashboard Notifications", "Notification badge on icon", "Unread notifications", "View app icon", "Badge count shown"),
    ("Dashboard Offline", "Dashboard visible offline", "No internet", "Open app", "Cached dashboard shown"),
    ("Dashboard Offline", "Offline banner shown", "No internet", "Check top of screen", "Offline banner displayed"),
]
for sub, title, pre, steps, exp in dash_data:
    rows.append(tc(f"TC{i:03d}", mod, sub, title, pre, steps, exp)); i += 1

# ── 4. INVENTORY MANAGEMENT (TC096–TC165) ───────────────────────────────────
mod = "Inventory Management"
inv_data = [
    ("View Inventory", "Inventory list loads", "Items in pantry", "Open Inventory tab", "All items listed"),
    ("View Inventory", "Item card shows name qty category", "Items exist", "View list", "Name qty category expiry shown on card"),
    ("View Inventory", "Sort by name A-Z", "Inventory loaded", "Tap Sort > Name A-Z", "Items sorted alphabetically"),
    ("View Inventory", "Sort by name Z-A", "Inventory loaded", "Tap Sort > Name Z-A", "Items sorted reverse alphabetically"),
    ("View Inventory", "Sort by expiry date", "Items with expiry", "Tap Sort > Expiry", "Earliest expiry first"),
    ("View Inventory", "Sort by quantity", "Inventory loaded", "Tap Sort > Quantity", "Lowest qty first"),
    ("View Inventory", "Filter by category", "Multiple categories", "Select category from filter", "Only that category shown"),
    ("View Inventory", "Filter by expiry status", "Items with various expiry", "Filter > Expiring Soon", "Only expiring items shown"),
    ("View Inventory", "Filter by location", "Items in different locations", "Filter > Location", "Filtered by pantry/fridge/freezer"),
    ("View Inventory", "Clear filters", "Filters applied", "Tap Clear Filters", "All items shown again"),
    ("View Inventory", "Grid view toggle", "List view active", "Tap Grid toggle", "Items shown in grid"),
    ("View Inventory", "List view toggle", "Grid view active", "Tap List toggle", "Items shown in list"),
    ("View Inventory", "Pull to refresh inventory", "On inventory screen", "Pull down", "Items refreshed from server"),
    ("View Inventory", "Empty state message", "No items in pantry", "Open inventory", "Empty state with add prompt shown"),
    ("Add Item", "Add item button visible", "On inventory screen", "View screen", "FAB or Add button present"),
    ("Add Item", "Add item form opens", "On inventory", "Tap Add", "Add item form/modal opens"),
    ("Add Item", "Enter item name", "Add form open", "Type 'Milk' in name field", "Name entered successfully"),
    ("Add Item", "Select category", "Add form open", "Tap Category dropdown", "Category options shown"),
    ("Add Item", "Enter quantity", "Add form open", "Enter quantity '2'", "Quantity saved"),
    ("Add Item", "Select unit", "Add form open", "Tap unit dropdown select Liters", "Unit set to Liters"),
    ("Add Item", "Enter expiry date", "Add form open", "Tap date picker select date", "Date selected and shown"),
    ("Add Item", "Select storage location", "Add form open", "Tap location select Fridge", "Location set to Fridge"),
    ("Add Item", "Add notes to item", "Add form open", "Enter notes text", "Notes saved with item"),
    ("Add Item", "Save item successfully", "All fields filled", "Tap Save", "Item added; list refreshes"),
    ("Add Item", "Validation: empty name", "Add form open", "Submit with empty name", "Error: name required"),
    ("Add Item", "Validation: negative quantity", "Add form open", "Enter qty -1", "Error: invalid quantity"),
    ("Add Item", "Add photo to item", "Add form open", "Tap Add Photo", "Camera/gallery opens"),
    ("Add Item", "Barcode scan from add form", "Add form open", "Tap Scan Barcode", "Barcode scanner opens"),
    ("Add Item", "Barcode auto-fills item name", "Barcode scanned", "Scan valid product", "Name category auto-populated"),
    ("Edit Item", "Edit item opens correctly", "Item exists", "Long press item > Edit", "Edit form pre-filled"),
    ("Edit Item", "Edit item name", "Edit form open", "Change name save", "Name updated in list"),
    ("Edit Item", "Edit quantity", "Edit form open", "Change qty save", "Qty updated"),
    ("Edit Item", "Edit expiry date", "Edit form open", "Change date save", "Date updated"),
    ("Edit Item", "Edit storage location", "Edit form open", "Change location save", "Location updated"),
    ("Edit Item", "Cancel edit", "Edit form open", "Tap Cancel", "No changes saved form closes"),
    ("Delete Item", "Delete via swipe", "Item in list", "Swipe left on item", "Delete option revealed"),
    ("Delete Item", "Confirm delete", "Delete option shown", "Tap Delete confirm", "Item removed from list"),
    ("Delete Item", "Cancel delete", "Delete confirm shown", "Tap Cancel", "Item remains in list"),
    ("Delete Item", "Undo delete", "Item just deleted", "Tap Undo in snackbar", "Item restored in list"),
    ("Delete Item", "Delete via context menu", "Item in list", "Long press > Delete", "Delete confirm shown"),
    ("Quantity Management", "Increment quantity", "Item detail open", "+ button visible", "Tap + quantity increases by 1"),
    ("Quantity Management", "Decrement quantity", "Item detail open", "Tap - button", "Quantity decreases by 1"),
    ("Quantity Management", "Quantity cannot go below 0", "Qty at 0", "Tap - button", "Button disabled or qty stays 0"),
    ("Quantity Management", "Bulk quantity update", "Multiple items selected", "Select items > Update Qty", "All selected updated"),
    ("Quantity Management", "Quantity unit conversion", "Item with unit set", "Change unit", "Qty converts proportionally"),
    ("Expiry Tracking", "Expired item highlighted red", "Item past expiry", "View inventory", "Item card shown in red/warning"),
    ("Expiry Tracking", "Expiring soon highlighted yellow", "Item expiring 3 days", "View inventory", "Item card shown in yellow"),
    ("Expiry Tracking", "Expiry date picker works", "Add/edit form", "Tap date picker", "Calendar shown date selectable"),
    ("Expiry Tracking", "Expiry notification fires", "Item expires tomorrow", "Background app overnight", "Notification shown next morning"),
    ("Expiry Tracking", "Remove expired item prompt", "Expired item exists", "Open item detail", "Prompt: discard or keep"),
    ("Categories", "Default categories shown", "First time", "Open category list", "Dairy Meat Produce etc listed"),
    ("Categories", "Add custom category", "On category screen", "Tap Add > Enter name save", "Category added to list"),
    ("Categories", "Delete custom category", "Custom category exists", "Long press > Delete", "Category removed"),
    ("Categories", "Rename custom category", "Custom category exists", "Long press > Rename", "Name updated"),
    ("Categories", "Category icon selection", "Adding category", "Tap icon picker", "Icon options shown selectable"),
    ("Categories", "Assign category color", "Adding category", "Tap color picker", "Color assigned to category"),
    ("Categories", "Items retain category on edit", "Item with category", "Edit item; don't change cat", "Category unchanged"),
    ("Locations", "Pantry location items", "Items in pantry", "Filter > Pantry", "Pantry items shown"),
    ("Locations", "Fridge location items", "Items in fridge", "Filter > Fridge", "Fridge items shown"),
    ("Locations", "Freezer location items", "Items in freezer", "Filter > Freezer", "Freezer items shown"),
    ("Locations", "Add custom location", "On locations settings", "Add 'Cabinet'", "Cabinet appears as location option"),
    ("Locations", "Delete custom location", "Custom location exists", "Delete it", "Location removed; items reassigned"),
    ("Bulk Actions", "Select multiple items", "On inventory", "Long press > select more", "Multi-select checkboxes shown"),
    ("Bulk Actions", "Bulk delete selected", "Items selected", "Tap Delete", "All selected deleted"),
    ("Bulk Actions", "Bulk move to list", "Items selected", "Tap Move to Shopping", "Items added to shopping list"),
    ("Bulk Actions", "Select all items", "On inventory", "Tap Select All", "All items checked"),
    ("Bulk Actions", "Deselect all", "All selected", "Tap Deselect All", "All unchecked"),
    ("Bulk Actions", "Bulk category change", "Items selected", "Change category", "Category updated for all selected"),
]
for sub, title, pre, steps, exp in inv_data:
    rows.append(tc(f"TC{i:03d}", mod, sub, title, pre, steps, exp)); i += 1

# ── 5. BARCODE SCANNER (TC166–TC190) ────────────────────────────────────────
mod = "Barcode Scanner"
bar_data = [
    ("Camera Permission", "Request camera permission", "First scan attempt", "Tap Scan", "Permission dialog appears"),
    ("Camera Permission", "Grant camera permission", "Permission dialog", "Tap Allow", "Camera opens scanner overlay"),
    ("Camera Permission", "Deny camera permission", "Permission dialog", "Tap Deny", "Error: need camera to scan"),
    ("Camera Permission", "Open settings on deny", "Camera denied", "Tap Open Settings", "Device settings open"),
    ("Scanner UI", "Scanner overlay displayed", "Camera open", "View scanner", "Crosshair/border guide shown"),
    ("Scanner UI", "Torch/flashlight toggle", "Scanner open", "Tap flashlight icon", "Torch toggles on/off"),
    ("Scanner UI", "Close scanner button", "Scanner open", "Tap X / Close", "Scanner closes returns to form"),
    ("Scan Success", "Scan valid barcode", "Scanner open product with barcode", "Align barcode in frame", "Product info fetched auto-filled"),
    ("Scan Success", "Product name auto-filled", "Scan success", "View add form", "Name populated from barcode DB"),
    ("Scan Success", "Category auto-filled", "Scan success", "View add form", "Category auto-populated"),
    ("Scan Success", "Scan confirmation feedback", "Scan success", "Observe", "Haptic + sound feedback given"),
    ("Scan Failure", "Unknown barcode", "Scanner open", "Scan unknown barcode", "Not found message; manual entry prompted"),
    ("Scan Failure", "Blurry scan handling", "Scanner open", "Present blurry barcode", "Scanner continues trying gracefully"),
    ("Scan Failure", "No barcode in frame", "Scanner open 10s", "No barcode presented", "Guidance text shown to user"),
    ("Manual Entry", "Manual barcode entry option", "Scanner open", "Tap Enter Manually", "Text field for barcode shown"),
    ("Manual Entry", "Submit manual barcode", "Manual field open", "Enter barcode number tap Go", "Product lookup performed"),
    ("Manual Entry", "Invalid manual barcode", "Manual entry", "Enter 'abc' tap Go", "Error: invalid barcode format"),
    ("History", "Recent scans history", "Multiple scans done", "View scan history", "Last 10 scans shown"),
    ("History", "Re-add from history", "Scan history viewed", "Tap item in history", "Add form pre-filled with item data"),
    ("History", "Clear scan history", "History exists", "Tap Clear History confirm", "History cleared"),
    ("Continuous Scan", "Continuous scan mode", "Scanner open", "Enable continuous mode", "Multiple items scanned sequentially"),
    ("Offline", "Scan offline falls back to manual", "No internet scanner open", "Scan barcode", "Offline message; manual entry shown"),
    ("QR Codes", "Scan QR code for recipe", "Scanner open QR shown", "Scan recipe QR", "Recipe imported into app"),
    ("QR Codes", "Scan family invite QR", "Scanner open", "Scan family QR code", "Family join request triggered"),
    ("Performance", "Scan speed under 2s", "Scanner open", "Scan clear barcode", "Product fetched in under 2 seconds"),
]
for sub, title, pre, steps, exp in bar_data:
    rows.append(tc(f"TC{i:03d}", mod, sub, title, pre, steps, exp)); i += 1

# ── 6. SHOPPING LIST (TC191–TC240) ──────────────────────────────────────────
mod = "Shopping List"
shop_data = [
    ("View List", "Shopping list screen loads", "Logged in", "Tap Shopping List tab", "Shopping list screen shown"),
    ("View List", "Empty list state", "No items in list", "Open shopping list", "Empty state with add prompt shown"),
    ("View List", "Items displayed correctly", "Items in list", "Open shopping list", "All items with name qty shown"),
    ("View List", "Checked off items shown at bottom", "Items checked", "View list", "Completed items move to bottom"),
    ("View List", "List scroll performance", "Many items in list", "Scroll quickly", "No lag observed"),
    ("Add Item", "Add item to shopping list", "On shopping list", "Tap + enter item name tap Add", "Item added to list"),
    ("Add Item", "Add from low-stock suggestion", "Low stock alerts exist", "Tap suggestion item", "Item added to shopping list"),
    ("Add Item", "Add item with quantity", "On shopping list", "Enter item and qty", "Item added with correct qty"),
    ("Add Item", "Add item with category", "On shopping list add form", "Select category", "Item saved with category"),
    ("Add Item", "Duplicate item warning", "Item already in list", "Add same item", "Warning: already in list"),
    ("Edit Item", "Edit shopping list item", "Item in list", "Tap item > Edit", "Edit form opens with data"),
    ("Edit Item", "Update item name", "Edit form open", "Change name save", "Name updated in list"),
    ("Edit Item", "Update item quantity", "Edit form open", "Change qty save", "Qty updated"),
    ("Complete Item", "Check off item", "Item in list", "Tap checkbox next to item", "Item marked complete strikethrough"),
    ("Complete Item", "Uncheck completed item", "Item checked", "Tap checkbox again", "Item unchecked back to active"),
    ("Complete Item", "Mark all as complete", "Items in list", "Tap Mark All", "All items checked"),
    ("Complete Item", "Clear completed items", "Completed items exist", "Tap Clear Completed", "Completed items removed"),
    ("Delete Item", "Delete item via swipe", "Item in list", "Swipe left > Delete", "Item removed"),
    ("Delete Item", "Undo delete", "Item deleted", "Tap Undo", "Item restored"),
    ("Sharing", "Share list with family", "Family connected", "Tap Share icon select member", "Member receives shared list"),
    ("Sharing", "Shared list visible to member", "List shared", "Member opens app", "Shared list appears in their app"),
    ("Sharing", "Collaborative edit sync", "2 users on shared list", "Both edit simultaneously", "Changes sync in real time"),
    ("Sharing", "Share list via link", "On shopping list", "Tap Share > Copy Link", "Shareable link copied"),
    ("Sharing", "Notify family on list update", "Family connected", "Add item to shared list", "Family notified of update"),
    ("Sorting", "Sort list by category", "Items in list", "Tap Sort > Category", "Items grouped by category"),
    ("Sorting", "Sort list by name", "Items in list", "Tap Sort > Name", "Alphabetical order"),
    ("Sorting", "Sort by priority", "Items with priority", "Tap Sort > Priority", "High priority items first"),
    ("Offline", "Add item offline", "No internet", "Add item to list", "Item saved locally synced when online"),
    ("Offline", "List visible offline", "No internet", "Open shopping list", "Cached list displayed"),
    ("Smart Suggest", "Auto-suggest from past purchases", "History exists", "Tap Add item field", "Past items suggested"),
    ("Smart Suggest", "Suggest based on recipes", "Recipe selected", "View suggestions", "Recipe ingredients shown in suggestions"),
    ("Smart Suggest", "Accept suggestion", "Suggestion shown", "Tap suggestion", "Item added to list"),
    ("Bulk Actions", "Bulk delete from shopping list", "Items selected", "Select all > Delete", "All deleted"),
    ("Bulk Actions", "Move items to pantry", "Shopping done", "Select items > Move to Pantry", "Items added to inventory"),
    ("Bulk Actions", "Bulk check off", "Items in list", "Select all > Check off", "All marked complete"),
    ("Categories", "Filter list by category", "Categorized items", "Filter > Dairy", "Only dairy items shown"),
    ("Categories", "Category groups in list", "Category sort active", "View list", "Category headers separate groups"),
    ("History", "View shopping history", "Past sessions", "Tap History", "Previous lists shown"),
    ("History", "Restore past list", "History available", "Select past list > Restore", "Items re-added to current list"),
    ("History", "Clear shopping history", "History exists", "Tap Clear History", "History cleared"),
    ("Notifications", "Reminder to shop", "Scheduled reminder set", "Time reaches reminder", "Push notification fires"),
    ("Notifications", "Set shopping reminder", "On shopping list", "Tap Reminder > Set time", "Reminder scheduled"),
    ("Notes", "Add note to list item", "Item in list", "Tap item > Add Note", "Note saved with item"),
    ("Notes", "View note on item", "Note exists", "View item", "Note icon visible tap shows note"),
    ("Priority", "Set item priority high", "Item in list", "Long press > Set Priority High", "High tag shown on item"),
    ("Priority", "Set item priority low", "Item in list", "Long press > Set Priority Low", "Low tag shown"),
    ("Store", "Assign item to store", "Multiple stores", "Tap item > Assign Store", "Store shown next to item"),
    ("Store", "Filter list by store", "Store assigned", "Filter > Store name", "Only that store's items shown"),
    ("Print", "Print shopping list", "List has items", "Tap Print/Share > Print", "Print dialog shown"),
    ("Export", "Export list as PDF", "List has items", "Tap Export > PDF", "PDF generated and shared"),
]
for sub, title, pre, steps, exp in shop_data:
    rows.append(tc(f"TC{i:03d}", mod, sub, title, pre, steps, exp)); i += 1

# ── 7. RECIPES (TC241–TC290) ─────────────────────────────────────────────────
mod = "Recipes"
recipe_data = [
    ("Browse", "Recipe list loads", "Logged in", "Open Recipes tab", "Recipe list shown"),
    ("Browse", "Recipe card shows image name", "Recipes available", "View list", "Image name cook-time shown on card"),
    ("Browse", "Filter by cuisine", "Recipes loaded", "Filter > Italian", "Italian recipes shown"),
    ("Browse", "Filter by diet", "Recipes loaded", "Filter > Vegetarian", "Vegetarian recipes shown"),
    ("Browse", "Filter by cook time", "Recipes loaded", "Filter > Under 30min", "Quick recipes shown"),
    ("Browse", "Search recipes by name", "Recipes loaded", "Search 'pasta'", "Matching recipes shown"),
    ("Browse", "Search by ingredient", "Recipes loaded", "Search by ingredient 'tomato'", "Recipes with tomato shown"),
    ("Browse", "No results state", "Recipes screen", "Search 'zxqwerty'", "No results message shown"),
    ("Browse", "Recipe sort by rating", "Recipes loaded", "Sort > Rating", "Highest rated first"),
    ("Browse", "Recipe sort by cook time", "Recipes loaded", "Sort > Cook time", "Quickest first"),
    ("Detail", "Recipe detail opens", "Recipe in list", "Tap recipe card", "Full recipe detail shown"),
    ("Detail", "Ingredients list shown", "Recipe detail open", "View ingredients section", "All ingredients with qty listed"),
    ("Detail", "Steps shown correctly", "Recipe detail open", "View steps section", "Numbered steps displayed"),
    ("Detail", "Serving size adjuster", "Recipe detail open", "Tap + on servings", "Ingredient quantities scale"),
    ("Detail", "Mark step as done", "Following recipe", "Tap step checkbox", "Step marked done"),
    ("Detail", "Timer for step", "Step with time shown", "Tap timer icon", "Countdown timer starts"),
    ("Detail", "Nutritional info shown", "Recipe detail", "Scroll to nutrition", "Calories macros shown"),
    ("Detail", "Save/favourite recipe", "Recipe detail open", "Tap heart icon", "Recipe added to favourites"),
    ("Detail", "Unsave recipe", "Recipe saved", "Tap heart icon again", "Recipe removed from favourites"),
    ("Detail", "Share recipe", "Recipe detail open", "Tap Share icon", "Share sheet opens"),
    ("Pantry Match", "Cook from pantry button", "Recipe detail open", "Tap Cook from Pantry", "Available ingredients highlighted"),
    ("Pantry Match", "Missing ingredients highlighted", "Cook from pantry", "View ingredient list", "Missing items shown in red"),
    ("Pantry Match", "Add missing to shopping list", "Missing items shown", "Tap Add to Shopping", "Missing items added to list"),
    ("Pantry Match", "Recipe compatibility score", "Pantry has items", "View recipe list", "% match shown per recipe"),
    ("Pantry Match", "Filter by fully available", "Recipes shown", "Filter > Can Cook Now", "Only 100% match recipes"),
    ("Create", "Create recipe button", "On recipes screen", "Tap Create Recipe", "Create form opens"),
    ("Create", "Enter recipe name", "Create form open", "Type recipe name", "Name entered"),
    ("Create", "Add ingredient to recipe", "Create form open", "Tap Add Ingredient enter details", "Ingredient added to list"),
    ("Create", "Add step to recipe", "Create form open", "Tap Add Step enter text", "Step added"),
    ("Create", "Add recipe photo", "Create form open", "Tap Add Photo", "Camera/gallery opens"),
    ("Create", "Set cook time", "Create form open", "Enter cook time", "Time saved"),
    ("Create", "Set servings", "Create form open", "Enter servings count", "Servings saved"),
    ("Create", "Save recipe", "Form filled", "Tap Save", "Recipe saved appears in list"),
    ("Create", "Validation: empty name", "Create form", "Submit without name", "Error: recipe name required"),
    ("Create", "Edit existing recipe", "Recipe exists", "Tap Edit on recipe", "Edit form opens pre-filled"),
    ("Create", "Delete own recipe", "Own recipe exists", "Tap Delete confirm", "Recipe removed from list"),
    ("Favourites", "Favourites list", "Recipes saved", "Tap Favourites tab", "All saved recipes shown"),
    ("Favourites", "Remove from favourites", "Recipe in favourites", "Unsave recipe", "Removed from favourites list"),
    ("Import", "Import recipe from URL", "Create screen", "Paste URL tap Import", "Recipe auto-parsed and filled"),
    ("Import", "Import from QR code", "Create screen", "Scan recipe QR", "Recipe data imported"),
    ("Meal Plan", "Add recipe to meal plan", "Recipe detail", "Tap Add to Meal Plan", "Meal plan calendar shown"),
    ("Meal Plan", "View meal plan", "Meal plan has recipes", "Navigate to Meal Plan", "Week view with recipes shown"),
    ("Meal Plan", "Remove from meal plan", "Recipe in plan", "Long press > Remove", "Recipe removed from day"),
    ("Meal Plan", "Generate shopping from plan", "Meal plan set", "Tap Generate Shopping List", "Missing ingredients added to list"),
    ("Rating", "Rate recipe", "Recipe detail", "Tap stars", "Rating submitted"),
    ("Rating", "Submit recipe review", "Recipe detail", "Tap review add text submit", "Review posted"),
    ("Rating", "View community ratings", "Recipe detail", "Scroll to ratings section", "Community ratings shown"),
    ("Offline", "Recipe viewable offline", "Recipe previously opened", "Open offline", "Cached recipe shown"),
    ("Offline", "Create recipe offline", "No internet create form", "Fill and save recipe", "Saved locally synced when online"),
    ("Performance", "Recipes load under 3s", "Logged in", "Open recipes tab", "List loads within 3 seconds"),
]
for sub, title, pre, steps, exp in recipe_data:
    rows.append(tc(f"TC{i:03d}", mod, sub, title, pre, steps, exp)); i += 1

# ── 8. FAMILY SYNC (TC291–TC330) ────────────────────────────────────────────
mod = "Family Sync"
fam_data = [
    ("Hub", "Family Sync Hub opens", "Logged in", "Navigate to Family Sync", "Hub screen with members shown"),
    ("Hub", "Family member list shown", "Family created", "View hub", "All members listed with roles"),
    ("Hub", "No family state", "No family group", "Open Family Sync", "Create/Join family prompt shown"),
    ("Hub", "Online status of members", "Family group active", "View hub", "Online/offline status shown per member"),
    ("Hub", "Member profile photos", "Members have photos", "View hub", "Avatars shown correctly"),
    ("Create Family", "Create family group", "No family yet", "Tap Create Family enter name", "Family created with user as admin"),
    ("Create Family", "Set family group name", "Creating family", "Enter 'Smith Family'", "Name set successfully"),
    ("Create Family", "Assign admin role", "Family created", "Select member > Make Admin", "Admin role assigned"),
    ("Invite", "Invite via email", "As admin", "Tap Invite enter email send", "Invitation email sent"),
    ("Invite", "Invite via SMS link", "As admin", "Tap Invite > SMS", "SMS with join link sent"),
    ("Invite", "Invite via QR code", "As admin", "Tap Invite > Show QR", "QR code displayed"),
    ("Invite", "Join via invite link", "Link received", "Tap link on device", "Join request sent to admin"),
    ("Invite", "Join via QR scan", "Invitee has QR", "Scan QR code", "Join request sent"),
    ("Invite", "Accept join request", "Pending request as admin", "Tap Accept", "Member added to group"),
    ("Invite", "Decline join request", "Pending request", "Tap Decline", "Request declined member not added"),
    ("Invite", "Invite expiry", "Invite link expired", "Tap expired link", "Error: link expired"),
    ("Permissions", "View-only member restriction", "View-only role set", "Try to edit pantry as view-only", "Edit blocked permission error"),
    ("Permissions", "Editor can add items", "Editor role set", "Add item", "Item added successfully"),
    ("Permissions", "Admin can remove members", "As admin", "Tap Remove on member confirm", "Member removed from group"),
    ("Permissions", "Non-admin cannot remove", "As regular member", "Try remove member", "Remove option not shown"),
    ("Permissions", "Admin can change roles", "As admin", "Change member role", "Role updated successfully"),
    ("Activity", "Family activity feed", "Family active", "View activity tab", "Recent actions by all members shown"),
    ("Activity", "Member adds item notification", "Family sync on", "Member adds item", "Notification sent to others"),
    ("Activity", "Real-time sync", "Two devices in family", "Edit item on one device", "Change appears on second device instantly"),
    ("Activity", "Shared shopping list", "Family group", "View shopping in hub", "Shared list shown"),
    ("Activity", "Member checkout activity", "Family shopping", "Member checks off item", "Activity shown in feed"),
    ("Leave Family", "Leave family group", "Member of family", "Tap Leave Family confirm", "Member removed from group"),
    ("Leave Family", "Admin cannot leave if only admin", "Only admin", "Tap Leave", "Error: assign new admin first"),
    ("Leave Family", "New admin on original admin leave", "Another admin exists", "Original admin leaves", "Group continues with new admin"),
    ("Leave Family", "Delete family group", "As admin", "Tap Delete Group confirm", "Group deleted all members notified"),
    ("Notifications", "Turn off family notifications", "Family member", "Toggle family notifs off in settings", "No more family notifications"),
    ("Notifications", "Family alert for low stock", "Stock low in shared pantry", "Stock reaches threshold", "All members notified"),
    ("Notifications", "Notify on new recipe added", "Family recipe sharing on", "Member adds recipe", "Notification sent"),
    ("Roles", "View roles assigned", "Family screen", "View member details", "Role (Admin/Editor/Viewer) shown"),
    ("Roles", "Bulk assign roles", "Multiple members", "Select members > Assign Role", "Role applied to all selected"),
    ("Roles", "Downgrade admin to member", "As super-admin", "Change role to Member", "Role downgraded successfully"),
    ("Settings", "Family settings screen", "In family group as admin", "Open settings", "Settings options shown"),
    ("Settings", "Rename family group", "In settings", "Tap Rename enter new name", "Family name updated everywhere"),
    ("Settings", "Set family visibility private", "In settings", "Toggle Private", "Family hidden from discovery"),
    ("Settings", "Enable/disable family recipes", "In settings", "Toggle recipe sharing", "Sharing enabled/disabled"),
]
for sub, title, pre, steps, exp in fam_data:
    rows.append(tc(f"TC{i:03d}", mod, sub, title, pre, steps, exp)); i += 1

# ── 9. NOTIFICATIONS & SETTINGS (TC331–TC370) ───────────────────────────────
mod = "Notifications & Settings"
notif_data = [
    ("Notifications", "Receive expiry push notification", "Item expiring tomorrow", "Background overnight", "Notification in tray next day"),
    ("Notifications", "Receive low-stock notification", "Item qty drops to 1", "Use last unit", "Low stock notification fired"),
    ("Notifications", "Notification tap routes correctly", "Notification received", "Tap notification", "Relevant screen opened in app"),
    ("Notifications", "Disable all notifications", "In settings", "Toggle all notifs off", "No notifications received"),
    ("Notifications", "Enable expiry notifications", "Notifs off", "Toggle expiry notifs on", "Expiry notifications resume"),
    ("Notifications", "Custom notification time", "In settings", "Set notification time 8 AM", "Notifications arrive at 8 AM"),
    ("Notifications", "Notification history", "Notifications received", "Open notification center", "Past notifications listed"),
    ("Notifications", "Clear all notifications", "Notif history exists", "Tap Clear All", "History cleared"),
    ("Notifications", "Do Not Disturb respect", "DND active on device", "Trigger notification", "No notification during DND"),
    ("Notifications", "Notification grouping", "Multiple alerts", "View notification tray", "Grouped under PantryWise"),
    ("App Settings", "Settings screen opens", "Logged in", "Navigate to Settings", "Settings menu shown"),
    ("App Settings", "Dark mode toggle", "On settings", "Toggle dark mode", "App switches to dark theme immediately"),
    ("App Settings", "System theme follow", "On settings", "Enable Follow System", "App theme matches device theme"),
    ("App Settings", "Language change", "On settings", "Change language to Spanish", "App relaunches in Spanish"),
    ("App Settings", "Currency setting", "On settings", "Change currency to EUR", "Prices shown in Euros"),
    ("App Settings", "Date format setting", "On settings", "Change date format DD/MM/YY", "Dates displayed in new format"),
    ("App Settings", "Measurement unit setting", "On settings", "Switch to Imperial", "Units changed to oz lbs etc"),
    ("App Settings", "Clear cache", "On settings", "Tap Clear Cache confirm", "Cache cleared success toast shown"),
    ("App Settings", "App version shown", "On settings/about", "View About section", "Current app version displayed"),
    ("App Settings", "Privacy policy link", "On settings", "Tap Privacy Policy", "Policy opens in web view"),
    ("App Settings", "Help & FAQ", "On settings", "Tap Help", "Help center opens"),
    ("App Settings", "Contact support", "On settings", "Tap Contact Us", "Email/chat support opened"),
    ("App Settings", "Rate the app link", "On settings", "Tap Rate App", "App store rating page opens"),
    ("App Settings", "Send feedback", "On settings", "Tap Feedback enter text send", "Feedback submitted"),
    ("App Settings", "Data export", "On settings", "Tap Export My Data", "Data downloaded as CSV/JSON"),
    ("App Settings", "Storage usage shown", "On settings", "View storage info", "App storage size shown"),
    ("App Settings", "Logout from settings", "Logged in", "Tap Logout in settings", "Logged out login screen shown"),
    ("Backup & Sync", "Auto-sync toggle", "On settings", "Toggle Auto-sync on", "Sync enabled confirmed"),
    ("Backup & Sync", "Manual sync trigger", "On settings", "Tap Sync Now", "Sync runs progress shown"),
    ("Backup & Sync", "Last synced time shown", "Sync done", "View settings", "Last synced timestamp shown"),
    ("Backup & Sync", "Cloud backup enabled", "On settings", "Enable cloud backup", "Backup starts shows progress"),
    ("Backup & Sync", "Restore from backup", "Backup exists", "Tap Restore select backup", "Data restored successfully"),
    ("Backup & Sync", "Backup frequency setting", "Backup enabled", "Set Daily/Weekly", "Frequency applied to backup schedule"),
    ("Backup & Sync", "Sync conflict resolution", "Conflict on sync", "Trigger conflict", "Prompt shown: keep local or remote"),
    ("Widgets", "Home screen widget setup", "App installed", "Add widget from home screen", "PantryWise widget shown"),
    ("Widgets", "Expiry widget shows data", "Widget added", "View home screen widget", "Expiring items shown in widget"),
    ("Widgets", "Shopping widget", "Widget added", "Add shopping widget", "Shopping list items shown"),
    ("Widgets", "Widget tap opens app", "Widget visible", "Tap widget", "App opens on relevant screen"),
    ("Accessibility", "VoiceOver / TalkBack support", "Accessibility on", "Navigate app via TalkBack", "All elements announced correctly"),
    ("Accessibility", "Font size scaling", "Large font in settings", "Change font size large", "App text scales correctly"),
]
for sub, title, pre, steps, exp in notif_data:
    rows.append(tc(f"TC{i:03d}", mod, sub, title, pre, steps, exp)); i += 1

# ── 10. PERFORMANCE & DEVICE (TC371–TC420) ──────────────────────────────────
mod = "Performance & Device"
perf_data = [
    ("Performance", "App cold start under 3s", "Fresh launch", "Launch app; measure time", "App ready in under 3 seconds"),
    ("Performance", "App warm start under 1.5s", "App in background", "Resume app; measure time", "Ready in under 1.5 seconds"),
    ("Performance", "Inventory scroll 60fps", "100+ items in inventory", "Scroll fast", "No frame drops observed"),
    ("Performance", "Image load performance", "Item with photo", "Navigate to item detail", "Photo loads under 1 second"),
    ("Performance", "Network request timeout handling", "Slow network", "Perform any action", "Timeout message shown gracefully"),
    ("Performance", "Memory usage under 200MB", "App running 10 min", "Check device memory", "Memory under 200MB"),
    ("Performance", "No ANR during heavy operations", "Many items", "Perform bulk edit", "No ANR dialog appears"),
    ("Performance", "Battery usage acceptable", "Use app 1 hour", "Check battery stats", "App not in battery drain list"),
    ("Performance", "Search debounce works", "In search mode", "Type quickly", "API called once per pause not each key"),
    ("Performance", "Lazy loading for images", "Image-heavy list", "Scroll list", "Images load as they enter view"),
    ("Offline Mode", "App usable offline", "No network", "Open app navigate", "Core screens accessible"),
    ("Offline Mode", "Offline indicator shown", "No network", "View top bar", "Offline badge/banner present"),
    ("Offline Mode", "Offline writes sync on reconnect", "Created items offline", "Reconnect to internet", "Offline items synced to server"),
    ("Offline Mode", "Conflict on sync resolved", "Offline edit + online edit same item", "Reconnect", "Conflict dialog shown"),
    ("Offline Mode", "Read-only mode on offline", "No network", "Try to add item", "Queued for sync toast shown"),
    ("Device Compatibility", "Runs on Android 10", "Android 10 device", "Launch and navigate", "All features work"),
    ("Device Compatibility", "Runs on Android 13", "Android 13 device", "Launch and navigate", "All features work"),
    ("Device Compatibility", "Runs on iOS 15", "iOS 15 device", "Launch and navigate", "All features work"),
    ("Device Compatibility", "Runs on iOS 17", "iOS 17 device", "Launch and navigate", "All features work"),
    ("Device Compatibility", "Small screen (5 inch)", "Small device", "Launch app", "No UI overlap or cutoff"),
    ("Device Compatibility", "Large screen (6.7 inch)", "Large device", "Launch app", "Layout uses space well"),
    ("Device Compatibility", "Tablet layout", "Tablet device", "Launch app", "Two-panel layout shown"),
    ("Device Compatibility", "Notch display support", "Notched device", "Launch app", "Content not hidden behind notch"),
    ("Device Compatibility", "Dynamic Island support (iOS)", "iPhone 14 Pro", "View top bar", "Notifications compatible with Dynamic Island"),
    ("Device Compatibility", "Foldable device support", "Foldable phone", "Launch folded; unfold", "Layout adapts to screen change"),
    ("Gestures", "Swipe to delete in list", "Item in list", "Swipe item left", "Delete option revealed"),
    ("Gestures", "Pull to refresh", "Any list screen", "Pull down", "Spinner shown data refreshed"),
    ("Gestures", "Pinch to zoom on images", "Item photo shown", "Pinch on photo", "Photo zooms in/out"),
    ("Gestures", "Long press for context menu", "Item in list", "Long press item", "Context menu shown"),
    ("Gestures", "Double tap to favorite recipe", "Recipe card", "Double tap", "Recipe saved to favourites"),
    ("Gestures", "Swipe between tabs", "On any main tab", "Swipe horizontally", "Moves to adjacent tab"),
    ("Gestures", "Back gesture (Android)", "On any sub-screen", "Swipe from left edge", "Navigates back"),
    ("Gestures", "Back gesture (iOS)", "On any sub-screen", "Swipe from left edge", "Navigates back"),
    ("Hardware", "Camera permission graceful", "Camera needed", "Deny camera", "Error with settings link shown"),
    ("Hardware", "Microphone permission", "Voice search used", "Deny microphone", "Error with settings link shown"),
    ("Hardware", "GPS/Location permission", "Store locator used", "Allow/deny location", "Handled gracefully"),
    ("Hardware", "Haptic feedback on actions", "Haptics enabled", "Tap save delete", "Device vibrates proportionally"),
    ("Hardware", "Background app refresh", "Background refresh on", "Background app 1 min", "Data updated when foregrounded"),
    ("Hardware", "Airplane mode handling", "Airplane mode on", "Open app", "Offline mode activates"),
    ("Hardware", "Low storage device", "Device storage <100MB", "Launch app", "Warning shown app functions"),
    ("Crash & Error", "No crash on low memory", "Device memory full", "Launch app", "App shows error does not crash"),
    ("Crash & Error", "Error boundary on component crash", "Force component error", "Trigger crash", "Error screen shown not blank"),
    ("Crash & Error", "API error handled gracefully", "Server returns 500", "Perform action", "User-friendly error message shown"),
    ("Crash & Error", "No crash on rapid navigation", "App running", "Rapidly tap between screens", "No crash or freeze"),
    ("Crash & Error", "App recovers from crash", "App crashed", "Relaunch app", "App opens cleanly to last state"),
    ("Crash & Error", "Analytics crash reported", "Crash monitoring on", "Trigger crash", "Crash logged in analytics dashboard"),
    ("Accessibility", "Font size accessibility", "Large font device setting", "Open app", "Text doesn't overflow cards"),
    ("Accessibility", "Color contrast compliance", "Any screen", "View UI elements", "Elements meet WCAG AA contrast"),
    ("Accessibility", "Screen reader navigation order", "TalkBack active", "Navigate screen", "Focus order is logical"),
    ("Accessibility", "Touch target size minimum 44pt", "Any screen", "View all buttons", "All targets >= 44x44 points"),
    ("Accessibility", "Reduce motion compliance", "Reduce motion on", "Open app", "Animations minimized"),
]
for sub, title, pre, steps, exp in perf_data:
    rows.append(tc(f"TC{i:03d}", mod, sub, title, pre, steps, exp)); i += 1

# ── Write CSV ────────────────────────────────────────────────────────────────
with open(OUTPUT_FILE, "w", newline="", encoding="utf-8-sig") as f:
    writer = csv.writer(f)
    writer.writerow(HEADERS)
    writer.writerows(rows)

print(f"✅ Generated {len(rows)} test cases → {OUTPUT_FILE}")
