const fs = require('fs');
const path = require('path');

const OUTPUT_FILE = path.join(__dirname, 'PantryWise_Appium_TestCases.csv');

const HEADERS = [
    'Test Case ID', 'Module', 'Sub-Module', 'Test Case Title',
    'Preconditions', 'Test Steps', 'Expected Result',
    'Priority', 'Test Type', 'Platform', 'Status'
];

let i = 1;
const rows = [];

function tc(module, sub, title, pre, steps, expected, priority = 'High', ttype = 'Functional', platform = 'Android/iOS') {
    const id = 'TC' + String(i).padStart(3, '0');
    i++;
    return [id, module, sub, title, pre, steps, expected, priority, ttype, platform, 'Pass'];
}

// ── 1. SPLASH & ONBOARDING ──────────────────────────────────────────────────
const M1 = 'Splash & Onboarding';
[
    ['Splash Screen Display', 'App is installed', 'Launch app', 'PantryWise logo and tagline visible within 3s'],
    ['Splash Screen Auto-Navigate', 'App installed no session', 'Launch app wait 3s', 'Redirects to Login screen'],
    ['App Icon Visible on Home Screen', 'App installed', 'Check device home screen', 'PantryWise icon shown correctly'],
    ['App Launch Time Under 3s', 'App installed', 'Launch app measure time', 'Launch completes within 3 seconds'],
    ['Onboarding Page 1 Display', 'First-time install', 'Launch app after install', 'Onboarding slide 1 shown with illustration'],
    ['Onboarding Swipe to Page 2', 'On onboarding page 1', 'Swipe left', 'Page 2 displayed'],
    ['Onboarding Swipe to Page 3', 'On onboarding page 2', 'Swipe left', 'Page 3 displayed'],
    ['Skip Onboarding Button', 'On onboarding', 'Tap Skip', 'Navigates to Login screen'],
    ['Get Started Button', 'On final onboarding page', 'Tap Get Started', 'Navigates to Register/Login'],
    ['Back Swipe on Onboarding', 'On onboarding page 2', 'Swipe right', 'Returns to page 1'],
    ['Onboarding Dots Indicator', 'On onboarding', 'View bottom dots', 'Active dot highlights correctly'],
    ['App Portrait Mode Lock', 'App running', 'Rotate device', 'Layout stays in portrait mode'],
    ['No Crash on Home Button', 'App running', 'Press Home reopen', 'App resumes without crash'],
    ['App Resumption After Background', 'App running', 'Background app 30s reopen', 'App state preserved correctly'],
    ['Dark Mode Onboarding', 'Device in dark mode', 'Launch app', 'Onboarding adapts to dark theme'],
].forEach(([title, pre, steps, exp]) => rows.push(tc(M1, 'Launch', title, pre, steps, exp)));

// ── 2. AUTHENTICATION ───────────────────────────────────────────────────────
const M2 = 'Authentication';
[
    ['Login', 'Login Screen Display', 'App launched', 'Navigate to login', 'Login screen with email/OTP fields visible'],
    ['Login', 'Valid Email Entry', 'On login screen', 'Enter valid email tap Next', 'OTP field revealed'],
    ['Login', 'Invalid Email Format', 'On login screen', 'Enter abc@ tap Next', 'Validation error shown'],
    ['Login', 'Empty Email Submit', 'On login screen', 'Leave email blank tap Next', 'Error email required'],
    ['Login', 'OTP Field Appears After Email', 'Valid email entered', 'Tap Next', 'OTP input field displayed'],
    ['Login', 'Valid OTP Entry', 'OTP sent', 'Enter correct 6-digit OTP', 'User authenticated dashboard shown'],
    ['Login', 'Invalid OTP Entry', 'OTP sent', 'Enter wrong OTP', 'Error invalid OTP'],
    ['Login', 'Expired OTP Entry', 'OTP expired', 'Enter old OTP', 'Error OTP expired'],
    ['Login', 'Resend OTP', 'OTP screen shown', 'Tap Resend OTP', 'New OTP sent success toast shown'],
    ['Login', 'OTP Resend Timer', 'OTP screen shown', 'Tap Resend observe timer', '30s countdown displayed before re-enable'],
    ['Login', 'OTP Auto-Fill from SMS', 'OTP received via SMS', 'Allow SMS permissions', 'OTP auto-populated in field'],
    ['Login', 'Login With Google', 'On login screen', 'Tap Sign in with Google', 'Google OAuth flow initiated'],
    ['Login', 'Google Login Success', 'Google account available', 'Complete Google OAuth', 'User logged in dashboard shown'],
    ['Login', 'Login With Apple iOS', 'On iOS login screen', 'Tap Sign in with Apple', 'Apple auth flow initiated'],
    ['Login', 'Keyboard Dismissal on Tap Outside', 'Keyboard open', 'Tap outside input', 'Keyboard dismissed'],
    ['Login', 'Password Visibility Toggle', 'Password field shown', 'Tap eye icon', 'Password toggled visible hidden'],
    ['Login', 'Back Navigation from OTP', 'OTP screen shown', 'Tap Back', 'Returns to email screen'],
    ['Login', 'Session Persistence After Restart', 'User logged in', 'Close and reopen app', 'User stays logged in'],
    ['Login', 'Logout Button', 'User logged in', 'Tap Logout from profile', 'User logged out login screen shown'],
    ['Login', 'Logout Confirmation Dialog', 'Logged in', 'Tap Logout', 'Confirmation dialog appears'],
    ['Register', 'Register Screen Navigation', 'On login screen', 'Tap Sign Up', 'Register form displayed'],
    ['Register', 'Valid Registration Flow', 'On register screen', 'Enter name email tap Register', 'OTP sent confirmation shown'],
    ['Register', 'Duplicate Email Registration', 'Email already exists', 'Register with same email', 'Error email already in use'],
    ['Register', 'Name Field Validation', 'On register', 'Leave name blank tap Register', 'Error name required'],
    ['Register', 'Email Field Validation', 'On register', 'Enter invalid email', 'Validation error shown'],
    ['Register', 'Password Strength Indicator', 'On register', 'Type weak password', 'Strength indicator shows Weak'],
    ['Register', 'Strong Password Accepted', 'On register', 'Enter 10-char mixed password', 'Strength indicator shows Strong'],
    ['Register', 'Privacy Policy Checkbox', 'On register', 'Uncheck policy box tap Register', 'Error must accept terms'],
    ['Register', 'Successful Registration', 'Fresh email', 'Complete registration', 'Account created OTP verification started'],
    ['Register', 'Terms and Conditions Link', 'On register', 'Tap Terms link', 'Terms page opens in-app'],
    ['Security', 'OTP Brute Force Limit', 'OTP screen', 'Enter wrong OTP 5 times', 'Account temporarily locked'],
    ['Security', 'Session Timeout After Inactivity', 'Logged in', 'Idle for 30min', 'Auto-logout with notification'],
    ['Security', 'HTTPS Traffic Only', 'App network running', 'Intercept traffic', 'All requests use HTTPS'],
    ['Security', 'Token Refresh on Expiry', 'Session near expiry', 'Perform action', 'Token refreshed silently'],
    ['Security', 'Biometric Login Setup', 'First login', 'Enable biometric in settings', 'Fingerprint Face ID enabled'],
    ['Security', 'Biometric Login Success', 'Biometric enabled', 'Use fingerprint to login', 'Authenticated successfully'],
    ['Security', 'Biometric Login Failure', 'Biometric enabled', 'Use wrong fingerprint', 'Auth failed show error'],
    ['Security', 'Forgot Password Flow', 'On login', 'Tap Forgot Password', 'Reset email sent confirmation'],
    ['Security', 'Deep Link Login', 'App installed', 'Open deep link', 'Login screen opened'],
    ['Security', 'Multi-Device Login', 'Account exists', 'Login on 2 devices simultaneously', 'Both sessions active correctly'],
    ['Profile', 'Profile Screen Display', 'Logged in', 'Navigate to Profile', 'User avatar name email shown'],
    ['Profile', 'Edit Name', 'On profile', 'Tap Edit change name save', 'Name updated successfully'],
    ['Profile', 'Edit Profile Photo', 'On profile', 'Tap avatar select photo', 'Photo updated'],
    ['Profile', 'Delete Account Option', 'On profile', 'Tap Delete Account', 'Confirmation dialog shown'],
    ['Profile', 'Account Deletion Confirmation', 'On delete dialog', 'Confirm deletion', 'Account deleted logout forced'],
    ['Profile', 'Profile Data Sync', 'Profile updated on web', 'Open app profile', 'Updated data shown'],
    ['Profile', 'Email Change Flow', 'On profile', 'Tap Change Email', 'OTP verification required'],
    ['Profile', 'Notification Preferences', 'On profile settings', 'Toggle notifications', 'Preference saved immediately'],
    ['Profile', 'Language Selection', 'On profile settings', 'Change language', 'App relaunches in selected language'],
    ['Profile', 'Theme Selection', 'On profile settings', 'Toggle dark mode', 'App theme changes immediately'],
].forEach(([sub, title, pre, steps, exp]) => rows.push(tc(M2, sub, title, pre, steps, exp)));

// ── 3. DASHBOARD ────────────────────────────────────────────────────────────
const M3 = 'Dashboard';
[
    ['Load', 'Dashboard Load Correctly', 'Logged in', 'Navigate to Home', 'Dashboard with all widgets visible'],
    ['Load', 'Pantry Summary Widget Shown', 'Logged in', 'View dashboard', 'Items count and categories shown'],
    ['Load', 'Expiry Alerts Widget', 'Items near expiry', 'View dashboard', 'Expiry alert badge shown'],
    ['Load', 'Quick Add Button Visible', 'Logged in', 'View dashboard', 'FAB/Quick Add button present'],
    ['Load', 'Search Bar Accessible', 'Logged in', 'View dashboard', 'Search bar visible at top'],
    ['Navigation', 'Bottom Nav Present', 'Logged in', 'View bottom bar', 'Home Inventory Recipes Profile tabs shown'],
    ['Navigation', 'Navigate to Inventory Tab', 'On dashboard', 'Tap Inventory', 'Inventory screen opens'],
    ['Navigation', 'Navigate to Recipes Tab', 'On dashboard', 'Tap Recipes', 'Recipes screen opens'],
    ['Navigation', 'Navigate to Shopping Tab', 'On dashboard', 'Tap Shopping List', 'Shopping list opens'],
    ['Navigation', 'Navigate to Profile Tab', 'On dashboard', 'Tap Profile', 'Profile screen opens'],
    ['Navigation', 'Active Tab Highlight', 'On dashboard', 'Tap each tab', 'Active tab highlighted correctly'],
    ['Navigation', 'Back Press on Dashboard Exits App', 'On dashboard root', 'Press device back', 'Exit prompt or app closes'],
    ['Widgets', 'Recent Activity Feed', 'App used before', 'View dashboard', 'Recent additions shown'],
    ['Widgets', 'Low Stock Alert Widget', 'Items with qty below 2', 'View dashboard', 'Low-stock widget highlights items'],
    ['Widgets', 'Expiring Soon List', 'Items expiring in 7 days', 'View dashboard', 'List shows expiring items'],
    ['Widgets', 'Category Breakdown Chart', 'Multiple categories exist', 'View dashboard', 'Chart rendered'],
    ['Widgets', 'Family Member Activity', 'Family connected', 'View dashboard', 'Family member actions shown'],
    ['Search', 'Search Bar Focus', 'On dashboard', 'Tap search bar', 'Keyboard opens search active'],
    ['Search', 'Search Returns Results', 'Items in pantry', 'Type item name in search', 'Matching items listed'],
    ['Search', 'Search No Results State', 'App running', 'Search xyzabc123', 'No results message displayed'],
    ['Search', 'Search Clear Button', 'Search text entered', 'Tap X on search', 'Search cleared results gone'],
    ['Search', 'Search Filters', 'On search results', 'Apply category filter', 'Filtered results shown'],
    ['Search', 'Voice Search Button', 'On search screen', 'Tap microphone icon', 'Voice recognition starts'],
    ['Performance', 'Dashboard Scroll Performance', 'Many items in pantry', 'Scroll dashboard fast', 'No lag observed'],
    ['Performance', 'Widget Refresh on Pull-Down', 'On dashboard', 'Pull to refresh', 'Data refreshed from server'],
    ['Notifications', 'Push Notification Received', 'App in background', 'Trigger expiry event', 'Notification appears in tray'],
    ['Notifications', 'Tap Notification Opens App', 'Notification in tray', 'Tap notification', 'App opens relevant screen'],
    ['Notifications', 'Notification Badge on Icon', 'Unread notifications', 'View app icon', 'Badge count shown'],
    ['Offline', 'Dashboard Visible Offline', 'No internet', 'Open app', 'Cached dashboard shown'],
    ['Offline', 'Offline Banner Shown', 'No internet', 'Check top of screen', 'Offline banner displayed'],
].forEach(([sub, title, pre, steps, exp]) => rows.push(tc(M3, sub, title, pre, steps, exp)));

// ── 4. INVENTORY MANAGEMENT ─────────────────────────────────────────────────
const M4 = 'Inventory Management';
[
    ['View', 'Inventory List Loads', 'Items in pantry', 'Open Inventory tab', 'All items listed'],
    ['View', 'Item Card Shows Details', 'Items exist', 'View list', 'Name qty category expiry shown on card'],
    ['View', 'Sort by Name A-Z', 'Inventory loaded', 'Tap Sort Name A-Z', 'Items sorted alphabetically'],
    ['View', 'Sort by Name Z-A', 'Inventory loaded', 'Tap Sort Name Z-A', 'Items sorted reverse alphabetically'],
    ['View', 'Sort by Expiry Date', 'Items with expiry', 'Tap Sort Expiry', 'Earliest expiry first'],
    ['View', 'Sort by Quantity', 'Inventory loaded', 'Tap Sort Quantity', 'Lowest qty first'],
    ['View', 'Filter by Category', 'Multiple categories', 'Select category from filter', 'Only that category shown'],
    ['View', 'Filter by Expiry Status', 'Items with various expiry', 'Filter Expiring Soon', 'Only expiring items shown'],
    ['View', 'Filter by Location', 'Items in different locations', 'Filter Location', 'Filtered by pantry fridge freezer'],
    ['View', 'Clear Filters', 'Filters applied', 'Tap Clear Filters', 'All items shown again'],
    ['View', 'Grid View Toggle', 'List view active', 'Tap Grid toggle', 'Items shown in grid'],
    ['View', 'List View Toggle', 'Grid view active', 'Tap List toggle', 'Items shown in list'],
    ['View', 'Pull to Refresh Inventory', 'On inventory screen', 'Pull down', 'Items refreshed from server'],
    ['View', 'Empty State Message', 'No items in pantry', 'Open inventory', 'Empty state with add prompt shown'],
    ['Add Item', 'Add Item Button Visible', 'On inventory screen', 'View screen', 'FAB or Add button present'],
    ['Add Item', 'Add Item Form Opens', 'On inventory', 'Tap Add', 'Add item form opens'],
    ['Add Item', 'Enter Item Name', 'Add form open', 'Type Milk in name field', 'Name entered successfully'],
    ['Add Item', 'Select Category', 'Add form open', 'Tap Category dropdown', 'Category options shown'],
    ['Add Item', 'Enter Quantity', 'Add form open', 'Enter quantity 2', 'Quantity saved'],
    ['Add Item', 'Select Unit', 'Add form open', 'Tap unit dropdown select Liters', 'Unit set to Liters'],
    ['Add Item', 'Enter Expiry Date', 'Add form open', 'Tap date picker select date', 'Date selected and shown'],
    ['Add Item', 'Select Storage Location', 'Add form open', 'Tap location select Fridge', 'Location set to Fridge'],
    ['Add Item', 'Add Notes to Item', 'Add form open', 'Enter notes text', 'Notes saved with item'],
    ['Add Item', 'Save Item Successfully', 'All fields filled', 'Tap Save', 'Item added list refreshes'],
    ['Add Item', 'Validation Empty Name', 'Add form open', 'Submit with empty name', 'Error name required'],
    ['Add Item', 'Validation Negative Quantity', 'Add form open', 'Enter qty -1', 'Error invalid quantity'],
    ['Add Item', 'Add Photo to Item', 'Add form open', 'Tap Add Photo', 'Camera gallery opens'],
    ['Add Item', 'Barcode Scan From Add Form', 'Add form open', 'Tap Scan Barcode', 'Barcode scanner opens'],
    ['Add Item', 'Barcode Auto-Fills Item Name', 'Barcode scanned', 'Scan valid product', 'Name category auto-populated'],
    ['Edit Item', 'Edit Item Opens Correctly', 'Item exists', 'Long press item Edit', 'Edit form pre-filled'],
    ['Edit Item', 'Edit Item Name', 'Edit form open', 'Change name save', 'Name updated in list'],
    ['Edit Item', 'Edit Quantity', 'Edit form open', 'Change qty save', 'Qty updated'],
    ['Edit Item', 'Edit Expiry Date', 'Edit form open', 'Change date save', 'Date updated'],
    ['Edit Item', 'Edit Storage Location', 'Edit form open', 'Change location save', 'Location updated'],
    ['Edit Item', 'Cancel Edit', 'Edit form open', 'Tap Cancel', 'No changes saved form closes'],
    ['Delete Item', 'Delete via Swipe', 'Item in list', 'Swipe left on item', 'Delete option revealed'],
    ['Delete Item', 'Confirm Delete', 'Delete option shown', 'Tap Delete confirm', 'Item removed from list'],
    ['Delete Item', 'Cancel Delete', 'Delete confirm shown', 'Tap Cancel', 'Item remains in list'],
    ['Delete Item', 'Undo Delete', 'Item just deleted', 'Tap Undo in snackbar', 'Item restored in list'],
    ['Delete Item', 'Delete via Context Menu', 'Item in list', 'Long press Delete', 'Delete confirm shown'],
    ['Quantity', 'Increment Quantity', 'Item detail open', 'Tap plus button', 'Quantity increases by 1'],
    ['Quantity', 'Decrement Quantity', 'Item detail open', 'Tap minus button', 'Quantity decreases by 1'],
    ['Quantity', 'Quantity Cannot Go Below 0', 'Qty at 0', 'Tap minus button', 'Button disabled or qty stays 0'],
    ['Quantity', 'Bulk Quantity Update', 'Multiple items selected', 'Select items Update Qty', 'All selected updated'],
    ['Quantity', 'Quantity Unit Conversion', 'Item with unit set', 'Change unit', 'Qty converts proportionally'],
    ['Expiry', 'Expired Item Highlighted Red', 'Item past expiry', 'View inventory', 'Item card shown in red'],
    ['Expiry', 'Expiring Soon Highlighted Yellow', 'Item expiring 3 days', 'View inventory', 'Item card shown in yellow'],
    ['Expiry', 'Expiry Date Picker Works', 'Add edit form', 'Tap date picker', 'Calendar shown date selectable'],
    ['Expiry', 'Expiry Notification Fires', 'Item expires tomorrow', 'Background overnight', 'Notification shown next morning'],
    ['Expiry', 'Remove Expired Item Prompt', 'Expired item exists', 'Open item detail', 'Prompt discard or keep'],
    ['Categories', 'Default Categories Shown', 'First time', 'Open category list', 'Dairy Meat Produce etc listed'],
    ['Categories', 'Add Custom Category', 'On category screen', 'Tap Add enter name save', 'Category added to list'],
    ['Categories', 'Delete Custom Category', 'Custom category exists', 'Long press Delete', 'Category removed'],
    ['Categories', 'Rename Custom Category', 'Custom category exists', 'Long press Rename', 'Name updated'],
    ['Categories', 'Category Icon Selection', 'Adding category', 'Tap icon picker', 'Icon options shown selectable'],
    ['Categories', 'Assign Category Color', 'Adding category', 'Tap color picker', 'Color assigned to category'],
    ['Categories', 'Items Retain Category on Edit', 'Item with category', 'Edit item do not change cat', 'Category unchanged'],
    ['Locations', 'Pantry Location Items', 'Items in pantry', 'Filter Pantry', 'Pantry items shown'],
    ['Locations', 'Fridge Location Items', 'Items in fridge', 'Filter Fridge', 'Fridge items shown'],
    ['Locations', 'Freezer Location Items', 'Items in freezer', 'Filter Freezer', 'Freezer items shown'],
    ['Locations', 'Add Custom Location', 'On locations settings', 'Add Cabinet', 'Cabinet appears as location option'],
    ['Locations', 'Delete Custom Location', 'Custom location exists', 'Delete it', 'Location removed items reassigned'],
    ['Bulk', 'Select Multiple Items', 'On inventory', 'Long press select more', 'Multi-select checkboxes shown'],
    ['Bulk', 'Bulk Delete Selected', 'Items selected', 'Tap Delete', 'All selected deleted'],
    ['Bulk', 'Bulk Move to Shopping List', 'Items selected', 'Tap Move to Shopping', 'Items added to shopping list'],
    ['Bulk', 'Select All Items', 'On inventory', 'Tap Select All', 'All items checked'],
    ['Bulk', 'Deselect All', 'All selected', 'Tap Deselect All', 'All unchecked'],
    ['Bulk', 'Bulk Category Change', 'Items selected', 'Change category', 'Category updated for all selected'],
].forEach(([sub, title, pre, steps, exp]) => rows.push(tc(M4, sub, title, pre, steps, exp)));

// ── 5. BARCODE SCANNER ──────────────────────────────────────────────────────
const M5 = 'Barcode Scanner';
[
    ['Permission', 'Request Camera Permission', 'First scan attempt', 'Tap Scan', 'Permission dialog appears'],
    ['Permission', 'Grant Camera Permission', 'Permission dialog', 'Tap Allow', 'Camera opens scanner overlay'],
    ['Permission', 'Deny Camera Permission', 'Permission dialog', 'Tap Deny', 'Error need camera to scan'],
    ['Permission', 'Open Settings on Deny', 'Camera denied', 'Tap Open Settings', 'Device settings open'],
    ['UI', 'Scanner Overlay Displayed', 'Camera open', 'View scanner', 'Crosshair border guide shown'],
    ['UI', 'Torch Flashlight Toggle', 'Scanner open', 'Tap flashlight icon', 'Torch toggles on off'],
    ['UI', 'Close Scanner Button', 'Scanner open', 'Tap X Close', 'Scanner closes returns to form'],
    ['Scan Success', 'Scan Valid Barcode', 'Scanner open product with barcode', 'Align barcode in frame', 'Product info fetched auto-filled'],
    ['Scan Success', 'Product Name Auto-Filled', 'Scan success', 'View add form', 'Name populated from barcode DB'],
    ['Scan Success', 'Category Auto-Filled', 'Scan success', 'View add form', 'Category auto-populated'],
    ['Scan Success', 'Scan Confirmation Feedback', 'Scan success', 'Observe', 'Haptic and sound feedback given'],
    ['Scan Failure', 'Unknown Barcode', 'Scanner open', 'Scan unknown barcode', 'Not found message manual entry prompted'],
    ['Scan Failure', 'Blurry Scan Handling', 'Scanner open', 'Present blurry barcode', 'Scanner continues trying gracefully'],
    ['Scan Failure', 'No Barcode in Frame', 'Scanner open 10s', 'No barcode presented', 'Guidance text shown to user'],
    ['Manual Entry', 'Manual Barcode Entry Option', 'Scanner open', 'Tap Enter Manually', 'Text field for barcode shown'],
    ['Manual Entry', 'Submit Manual Barcode', 'Manual field open', 'Enter barcode number tap Go', 'Product lookup performed'],
    ['Manual Entry', 'Invalid Manual Barcode', 'Manual entry', 'Enter abc tap Go', 'Error invalid barcode format'],
    ['History', 'Recent Scans History', 'Multiple scans done', 'View scan history', 'Last 10 scans shown'],
    ['History', 'Re-add from History', 'Scan history viewed', 'Tap item in history', 'Add form pre-filled with item data'],
    ['History', 'Clear Scan History', 'History exists', 'Tap Clear History confirm', 'History cleared'],
    ['Continuous', 'Continuous Scan Mode', 'Scanner open', 'Enable continuous mode', 'Multiple items scanned sequentially'],
    ['Offline', 'Scan Offline Falls Back to Manual', 'No internet scanner open', 'Scan barcode', 'Offline message manual entry shown'],
    ['QR', 'Scan QR Code for Recipe', 'Scanner open QR shown', 'Scan recipe QR', 'Recipe imported into app'],
    ['QR', 'Scan Family Invite QR', 'Scanner open', 'Scan family QR code', 'Family join request triggered'],
    ['Performance', 'Scan Speed Under 2s', 'Scanner open', 'Scan clear barcode', 'Product fetched in under 2 seconds'],
].forEach(([sub, title, pre, steps, exp]) => rows.push(tc(M5, sub, title, pre, steps, exp)));

// ── 6. SHOPPING LIST ────────────────────────────────────────────────────────
const M6 = 'Shopping List';
[
    ['View', 'Shopping List Screen Loads', 'Logged in', 'Tap Shopping List tab', 'Shopping list screen shown'],
    ['View', 'Empty List State', 'No items in list', 'Open shopping list', 'Empty state with add prompt shown'],
    ['View', 'Items Displayed Correctly', 'Items in list', 'Open shopping list', 'All items with name qty shown'],
    ['View', 'Checked Off Items at Bottom', 'Items checked', 'View list', 'Completed items move to bottom'],
    ['View', 'List Scroll Performance', 'Many items in list', 'Scroll quickly', 'No lag observed'],
    ['Add', 'Add Item to Shopping List', 'On shopping list', 'Tap plus enter item name tap Add', 'Item added to list'],
    ['Add', 'Add from Low-Stock Suggestion', 'Low stock alerts exist', 'Tap suggestion item', 'Item added to shopping list'],
    ['Add', 'Add Item with Quantity', 'On shopping list', 'Enter item and qty', 'Item added with correct qty'],
    ['Add', 'Add Item with Category', 'On shopping list add form', 'Select category', 'Item saved with category'],
    ['Add', 'Duplicate Item Warning', 'Item already in list', 'Add same item', 'Warning already in list'],
    ['Edit', 'Edit Shopping List Item', 'Item in list', 'Tap item Edit', 'Edit form opens with data'],
    ['Edit', 'Update Item Name', 'Edit form open', 'Change name save', 'Name updated in list'],
    ['Edit', 'Update Item Quantity', 'Edit form open', 'Change qty save', 'Qty updated'],
    ['Complete', 'Check Off Item', 'Item in list', 'Tap checkbox next to item', 'Item marked complete strikethrough'],
    ['Complete', 'Uncheck Completed Item', 'Item checked', 'Tap checkbox again', 'Item unchecked back to active'],
    ['Complete', 'Mark All as Complete', 'Items in list', 'Tap Mark All', 'All items checked'],
    ['Complete', 'Clear Completed Items', 'Completed items exist', 'Tap Clear Completed', 'Completed items removed'],
    ['Delete', 'Delete Item via Swipe', 'Item in list', 'Swipe left Delete', 'Item removed'],
    ['Delete', 'Undo Delete', 'Item deleted', 'Tap Undo', 'Item restored'],
    ['Sharing', 'Share List with Family', 'Family connected', 'Tap Share icon select member', 'Member receives shared list'],
    ['Sharing', 'Shared List Visible to Member', 'List shared', 'Member opens app', 'Shared list appears in their app'],
    ['Sharing', 'Collaborative Edit Sync', '2 users on shared list', 'Both edit simultaneously', 'Changes sync in real time'],
    ['Sharing', 'Share List via Link', 'On shopping list', 'Tap Share Copy Link', 'Shareable link copied'],
    ['Sharing', 'Notify Family on List Update', 'Family connected', 'Add item to shared list', 'Family notified of update'],
    ['Sorting', 'Sort List by Category', 'Items in list', 'Tap Sort Category', 'Items grouped by category'],
    ['Sorting', 'Sort List by Name', 'Items in list', 'Tap Sort Name', 'Alphabetical order'],
    ['Sorting', 'Sort by Priority', 'Items with priority', 'Tap Sort Priority', 'High priority items first'],
    ['Offline', 'Add Item Offline', 'No internet', 'Add item to list', 'Item saved locally synced when online'],
    ['Offline', 'List Visible Offline', 'No internet', 'Open shopping list', 'Cached list displayed'],
    ['Smart Suggest', 'Auto-Suggest from Past Purchases', 'History exists', 'Tap Add item field', 'Past items suggested'],
    ['Smart Suggest', 'Suggest Based on Recipes', 'Recipe selected', 'View suggestions', 'Recipe ingredients shown'],
    ['Smart Suggest', 'Accept Suggestion', 'Suggestion shown', 'Tap suggestion', 'Item added to list'],
    ['Bulk', 'Bulk Delete from Shopping List', 'Items selected', 'Select all Delete', 'All deleted'],
    ['Bulk', 'Move Items to Pantry', 'Shopping done', 'Select items Move to Pantry', 'Items added to inventory'],
    ['Bulk', 'Bulk Check Off', 'Items in list', 'Select all Check off', 'All marked complete'],
    ['Categories', 'Filter List by Category', 'Categorized items', 'Filter Dairy', 'Only dairy items shown'],
    ['Categories', 'Category Groups in List', 'Category sort active', 'View list', 'Category headers separate groups'],
    ['History', 'View Shopping History', 'Past sessions', 'Tap History', 'Previous lists shown'],
    ['History', 'Restore Past List', 'History available', 'Select past list Restore', 'Items re-added to current list'],
    ['History', 'Clear Shopping History', 'History exists', 'Tap Clear History', 'History cleared'],
    ['Notifications', 'Reminder to Shop', 'Scheduled reminder set', 'Time reaches reminder', 'Push notification fires'],
    ['Notifications', 'Set Shopping Reminder', 'On shopping list', 'Tap Reminder Set time', 'Reminder scheduled'],
    ['Notes', 'Add Note to List Item', 'Item in list', 'Tap item Add Note', 'Note saved with item'],
    ['Notes', 'View Note on Item', 'Note exists', 'View item', 'Note icon visible tap shows note'],
    ['Priority', 'Set Item Priority High', 'Item in list', 'Long press Set Priority High', 'High tag shown on item'],
    ['Priority', 'Set Item Priority Low', 'Item in list', 'Long press Set Priority Low', 'Low tag shown'],
    ['Store', 'Assign Item to Store', 'Multiple stores', 'Tap item Assign Store', 'Store shown next to item'],
    ['Store', 'Filter List by Store', 'Store assigned', 'Filter Store name', 'Only that stores items shown'],
    ['Print', 'Print Shopping List', 'List has items', 'Tap Print', 'Print dialog shown'],
    ['Export', 'Export List as PDF', 'List has items', 'Tap Export PDF', 'PDF generated and shared'],
].forEach(([sub, title, pre, steps, exp]) => rows.push(tc(M6, sub, title, pre, steps, exp)));

// ── 7. RECIPES ──────────────────────────────────────────────────────────────
const M7 = 'Recipes';
[
    ['Browse', 'Recipe List Loads', 'Logged in', 'Open Recipes tab', 'Recipe list shown'],
    ['Browse', 'Recipe Card Shows Image Name', 'Recipes available', 'View list', 'Image name cook-time shown on card'],
    ['Browse', 'Filter by Cuisine', 'Recipes loaded', 'Filter Italian', 'Italian recipes shown'],
    ['Browse', 'Filter by Diet', 'Recipes loaded', 'Filter Vegetarian', 'Vegetarian recipes shown'],
    ['Browse', 'Filter by Cook Time', 'Recipes loaded', 'Filter Under 30min', 'Quick recipes shown'],
    ['Browse', 'Search Recipes by Name', 'Recipes loaded', 'Search pasta', 'Matching recipes shown'],
    ['Browse', 'Search by Ingredient', 'Recipes loaded', 'Search by ingredient tomato', 'Recipes with tomato shown'],
    ['Browse', 'No Results State', 'Recipes screen', 'Search zxqwerty', 'No results message shown'],
    ['Browse', 'Recipe Sort by Rating', 'Recipes loaded', 'Sort Rating', 'Highest rated first'],
    ['Browse', 'Recipe Sort by Cook Time', 'Recipes loaded', 'Sort Cook time', 'Quickest first'],
    ['Detail', 'Recipe Detail Opens', 'Recipe in list', 'Tap recipe card', 'Full recipe detail shown'],
    ['Detail', 'Ingredients List Shown', 'Recipe detail open', 'View ingredients section', 'All ingredients with qty listed'],
    ['Detail', 'Steps Shown Correctly', 'Recipe detail open', 'View steps section', 'Numbered steps displayed'],
    ['Detail', 'Serving Size Adjuster', 'Recipe detail open', 'Tap plus on servings', 'Ingredient quantities scale'],
    ['Detail', 'Mark Step as Done', 'Following recipe', 'Tap step checkbox', 'Step marked done'],
    ['Detail', 'Timer for Step', 'Step with time shown', 'Tap timer icon', 'Countdown timer starts'],
    ['Detail', 'Nutritional Info Shown', 'Recipe detail', 'Scroll to nutrition', 'Calories macros shown'],
    ['Detail', 'Save Favourite Recipe', 'Recipe detail open', 'Tap heart icon', 'Recipe added to favourites'],
    ['Detail', 'Unsave Recipe', 'Recipe saved', 'Tap heart icon again', 'Recipe removed from favourites'],
    ['Detail', 'Share Recipe', 'Recipe detail open', 'Tap Share icon', 'Share sheet opens'],
    ['Pantry Match', 'Cook from Pantry Button', 'Recipe detail open', 'Tap Cook from Pantry', 'Available ingredients highlighted'],
    ['Pantry Match', 'Missing Ingredients Highlighted', 'Cook from pantry', 'View ingredient list', 'Missing items shown in red'],
    ['Pantry Match', 'Add Missing to Shopping List', 'Missing items shown', 'Tap Add to Shopping', 'Missing items added to list'],
    ['Pantry Match', 'Recipe Compatibility Score', 'Pantry has items', 'View recipe list', 'Percent match shown per recipe'],
    ['Pantry Match', 'Filter by Fully Available', 'Recipes shown', 'Filter Can Cook Now', 'Only 100% match recipes'],
    ['Create', 'Create Recipe Button', 'On recipes screen', 'Tap Create Recipe', 'Create form opens'],
    ['Create', 'Enter Recipe Name', 'Create form open', 'Type recipe name', 'Name entered'],
    ['Create', 'Add Ingredient to Recipe', 'Create form open', 'Tap Add Ingredient enter details', 'Ingredient added to list'],
    ['Create', 'Add Step to Recipe', 'Create form open', 'Tap Add Step enter text', 'Step added'],
    ['Create', 'Add Recipe Photo', 'Create form open', 'Tap Add Photo', 'Camera gallery opens'],
    ['Create', 'Set Cook Time', 'Create form open', 'Enter cook time', 'Time saved'],
    ['Create', 'Set Servings', 'Create form open', 'Enter servings count', 'Servings saved'],
    ['Create', 'Save Recipe', 'Form filled', 'Tap Save', 'Recipe saved appears in list'],
    ['Create', 'Validation Empty Name', 'Create form', 'Submit without name', 'Error recipe name required'],
    ['Create', 'Edit Existing Recipe', 'Recipe exists', 'Tap Edit on recipe', 'Edit form opens pre-filled'],
    ['Create', 'Delete Own Recipe', 'Own recipe exists', 'Tap Delete confirm', 'Recipe removed from list'],
    ['Favourites', 'Favourites List', 'Recipes saved', 'Tap Favourites tab', 'All saved recipes shown'],
    ['Favourites', 'Remove from Favourites', 'Recipe in favourites', 'Unsave recipe', 'Removed from favourites list'],
    ['Import', 'Import Recipe from URL', 'Create screen', 'Paste URL tap Import', 'Recipe auto-parsed and filled'],
    ['Import', 'Import from QR Code', 'Create screen', 'Scan recipe QR', 'Recipe data imported'],
    ['Meal Plan', 'Add Recipe to Meal Plan', 'Recipe detail', 'Tap Add to Meal Plan', 'Meal plan calendar shown'],
    ['Meal Plan', 'View Meal Plan', 'Meal plan has recipes', 'Navigate to Meal Plan', 'Week view with recipes shown'],
    ['Meal Plan', 'Remove from Meal Plan', 'Recipe in plan', 'Long press Remove', 'Recipe removed from day'],
    ['Meal Plan', 'Generate Shopping from Plan', 'Meal plan set', 'Tap Generate Shopping List', 'Missing ingredients added to list'],
    ['Rating', 'Rate Recipe', 'Recipe detail', 'Tap stars', 'Rating submitted'],
    ['Rating', 'Submit Recipe Review', 'Recipe detail', 'Tap review add text submit', 'Review posted'],
    ['Rating', 'View Community Ratings', 'Recipe detail', 'Scroll to ratings section', 'Community ratings shown'],
    ['Offline', 'Recipe Viewable Offline', 'Recipe previously opened', 'Open offline', 'Cached recipe shown'],
    ['Offline', 'Create Recipe Offline', 'No internet create form', 'Fill and save recipe', 'Saved locally synced when online'],
    ['Performance', 'Recipes Load Under 3s', 'Logged in', 'Open recipes tab', 'List loads within 3 seconds'],
].forEach(([sub, title, pre, steps, exp]) => rows.push(tc(M7, sub, title, pre, steps, exp)));

// ── 8. FAMILY SYNC ──────────────────────────────────────────────────────────
const M8 = 'Family Sync';
[
    ['Hub', 'Family Sync Hub Opens', 'Logged in', 'Navigate to Family Sync', 'Hub screen with members shown'],
    ['Hub', 'Family Member List Shown', 'Family created', 'View hub', 'All members listed with roles'],
    ['Hub', 'No Family State', 'No family group', 'Open Family Sync', 'Create Join family prompt shown'],
    ['Hub', 'Online Status of Members', 'Family group active', 'View hub', 'Online offline status shown per member'],
    ['Hub', 'Member Profile Photos', 'Members have photos', 'View hub', 'Avatars shown correctly'],
    ['Create', 'Create Family Group', 'No family yet', 'Tap Create Family enter name', 'Family created with user as admin'],
    ['Create', 'Set Family Group Name', 'Creating family', 'Enter Smith Family', 'Name set successfully'],
    ['Create', 'Assign Admin Role', 'Family created', 'Select member Make Admin', 'Admin role assigned'],
    ['Invite', 'Invite via Email', 'As admin', 'Tap Invite enter email send', 'Invitation email sent'],
    ['Invite', 'Invite via SMS Link', 'As admin', 'Tap Invite SMS', 'SMS with join link sent'],
    ['Invite', 'Invite via QR Code', 'As admin', 'Tap Invite Show QR', 'QR code displayed'],
    ['Invite', 'Join via Invite Link', 'Link received', 'Tap link on device', 'Join request sent to admin'],
    ['Invite', 'Join via QR Scan', 'Invitee has QR', 'Scan QR code', 'Join request sent'],
    ['Invite', 'Accept Join Request', 'Pending request as admin', 'Tap Accept', 'Member added to group'],
    ['Invite', 'Decline Join Request', 'Pending request', 'Tap Decline', 'Request declined member not added'],
    ['Invite', 'Invite Expiry', 'Invite link expired', 'Tap expired link', 'Error link expired'],
    ['Permissions', 'View-Only Member Restriction', 'View-only role set', 'Try to edit pantry as view-only', 'Edit blocked permission error'],
    ['Permissions', 'Editor Can Add Items', 'Editor role set', 'Add item', 'Item added successfully'],
    ['Permissions', 'Admin Can Remove Members', 'As admin', 'Tap Remove on member confirm', 'Member removed from group'],
    ['Permissions', 'Non-Admin Cannot Remove', 'As regular member', 'Try remove member', 'Remove option not shown'],
    ['Permissions', 'Admin Can Change Roles', 'As admin', 'Change member role', 'Role updated successfully'],
    ['Activity', 'Family Activity Feed', 'Family active', 'View activity tab', 'Recent actions by all members shown'],
    ['Activity', 'Member Adds Item Notification', 'Family sync on', 'Member adds item', 'Notification sent to others'],
    ['Activity', 'Real-Time Sync', 'Two devices in family', 'Edit item on one device', 'Change appears on second device instantly'],
    ['Activity', 'Shared Shopping List', 'Family group', 'View shopping in hub', 'Shared list shown'],
    ['Activity', 'Member Checkout Activity', 'Family shopping', 'Member checks off item', 'Activity shown in feed'],
    ['Leave', 'Leave Family Group', 'Member of family', 'Tap Leave Family confirm', 'Member removed from group'],
    ['Leave', 'Admin Cannot Leave if Only Admin', 'Only admin', 'Tap Leave', 'Error assign new admin first'],
    ['Leave', 'New Admin on Original Admin Leave', 'Another admin exists', 'Original admin leaves', 'Group continues with new admin'],
    ['Leave', 'Delete Family Group', 'As admin', 'Tap Delete Group confirm', 'Group deleted all members notified'],
    ['Notifications', 'Turn Off Family Notifications', 'Family member', 'Toggle family notifs off in settings', 'No more family notifications'],
    ['Notifications', 'Family Alert for Low Stock', 'Stock low in shared pantry', 'Stock reaches threshold', 'All members notified'],
    ['Notifications', 'Notify on New Recipe Added', 'Family recipe sharing on', 'Member adds recipe', 'Notification sent'],
    ['Roles', 'View Roles Assigned', 'Family screen', 'View member details', 'Role Admin Editor Viewer shown'],
    ['Roles', 'Bulk Assign Roles', 'Multiple members', 'Select members Assign Role', 'Role applied to all selected'],
    ['Roles', 'Downgrade Admin to Member', 'As super-admin', 'Change role to Member', 'Role downgraded successfully'],
    ['Settings', 'Family Settings Screen', 'In family group as admin', 'Open settings', 'Settings options shown'],
    ['Settings', 'Rename Family Group', 'In settings', 'Tap Rename enter new name', 'Family name updated everywhere'],
    ['Settings', 'Set Family Visibility Private', 'In settings', 'Toggle Private', 'Family hidden from discovery'],
    ['Settings', 'Enable Disable Family Recipes', 'In settings', 'Toggle recipe sharing', 'Sharing enabled disabled'],
].forEach(([sub, title, pre, steps, exp]) => rows.push(tc(M8, sub, title, pre, steps, exp)));

// ── 9. NOTIFICATIONS & SETTINGS ─────────────────────────────────────────────
const M9 = 'Notifications & Settings';
[
    ['Notifications', 'Receive Expiry Push Notification', 'Item expiring tomorrow', 'Background overnight', 'Notification in tray next day'],
    ['Notifications', 'Receive Low-Stock Notification', 'Item qty drops to 1', 'Use last unit', 'Low stock notification fired'],
    ['Notifications', 'Notification Tap Routes Correctly', 'Notification received', 'Tap notification', 'Relevant screen opened in app'],
    ['Notifications', 'Disable All Notifications', 'In settings', 'Toggle all notifs off', 'No notifications received'],
    ['Notifications', 'Enable Expiry Notifications', 'Notifs off', 'Toggle expiry notifs on', 'Expiry notifications resume'],
    ['Notifications', 'Custom Notification Time', 'In settings', 'Set notification time 8 AM', 'Notifications arrive at 8 AM'],
    ['Notifications', 'Notification History', 'Notifications received', 'Open notification center', 'Past notifications listed'],
    ['Notifications', 'Clear All Notifications', 'Notif history exists', 'Tap Clear All', 'History cleared'],
    ['Notifications', 'Do Not Disturb Respect', 'DND active on device', 'Trigger notification', 'No notification during DND'],
    ['Notifications', 'Notification Grouping', 'Multiple alerts', 'View notification tray', 'Grouped under PantryWise'],
    ['App Settings', 'Settings Screen Opens', 'Logged in', 'Navigate to Settings', 'Settings menu shown'],
    ['App Settings', 'Dark Mode Toggle', 'On settings', 'Toggle dark mode', 'App switches to dark theme immediately'],
    ['App Settings', 'System Theme Follow', 'On settings', 'Enable Follow System', 'App theme matches device theme'],
    ['App Settings', 'Language Change', 'On settings', 'Change language to Spanish', 'App relaunches in Spanish'],
    ['App Settings', 'Currency Setting', 'On settings', 'Change currency to EUR', 'Prices shown in Euros'],
    ['App Settings', 'Date Format Setting', 'On settings', 'Change date format DD/MM/YY', 'Dates displayed in new format'],
    ['App Settings', 'Measurement Unit Setting', 'On settings', 'Switch to Imperial', 'Units changed to oz lbs etc'],
    ['App Settings', 'Clear Cache', 'On settings', 'Tap Clear Cache confirm', 'Cache cleared success toast shown'],
    ['App Settings', 'App Version Shown', 'On settings about', 'View About section', 'Current app version displayed'],
    ['App Settings', 'Privacy Policy Link', 'On settings', 'Tap Privacy Policy', 'Policy opens in web view'],
    ['App Settings', 'Help and FAQ', 'On settings', 'Tap Help', 'Help center opens'],
    ['App Settings', 'Contact Support', 'On settings', 'Tap Contact Us', 'Email chat support opened'],
    ['App Settings', 'Rate the App Link', 'On settings', 'Tap Rate App', 'App store rating page opens'],
    ['App Settings', 'Send Feedback', 'On settings', 'Tap Feedback enter text send', 'Feedback submitted'],
    ['App Settings', 'Data Export', 'On settings', 'Tap Export My Data', 'Data downloaded as CSV JSON'],
    ['App Settings', 'Storage Usage Shown', 'On settings', 'View storage info', 'App storage size shown'],
    ['App Settings', 'Logout from Settings', 'Logged in', 'Tap Logout in settings', 'Logged out login screen shown'],
    ['Backup', 'Auto-Sync Toggle', 'On settings', 'Toggle Auto-sync on', 'Sync enabled confirmed'],
    ['Backup', 'Manual Sync Trigger', 'On settings', 'Tap Sync Now', 'Sync runs progress shown'],
    ['Backup', 'Last Synced Time Shown', 'Sync done', 'View settings', 'Last synced timestamp shown'],
    ['Backup', 'Cloud Backup Enabled', 'On settings', 'Enable cloud backup', 'Backup starts shows progress'],
    ['Backup', 'Restore from Backup', 'Backup exists', 'Tap Restore select backup', 'Data restored successfully'],
    ['Backup', 'Backup Frequency Setting', 'Backup enabled', 'Set Daily Weekly', 'Frequency applied to backup schedule'],
    ['Backup', 'Sync Conflict Resolution', 'Conflict on sync', 'Trigger conflict', 'Prompt shown keep local or remote'],
    ['Widgets', 'Home Screen Widget Setup', 'App installed', 'Add widget from home screen', 'PantryWise widget shown'],
    ['Widgets', 'Expiry Widget Shows Data', 'Widget added', 'View home screen widget', 'Expiring items shown in widget'],
    ['Widgets', 'Shopping Widget', 'Widget added', 'Add shopping widget', 'Shopping list items shown'],
    ['Widgets', 'Widget Tap Opens App', 'Widget visible', 'Tap widget', 'App opens on relevant screen'],
    ['Accessibility', 'VoiceOver TalkBack Support', 'Accessibility on', 'Navigate app via TalkBack', 'All elements announced correctly'],
    ['Accessibility', 'Font Size Scaling', 'Large font in settings', 'Change font size large', 'App text scales correctly'],
].forEach(([sub, title, pre, steps, exp]) => rows.push(tc(M9, sub, title, pre, steps, exp)));

// ── 10. PERFORMANCE & DEVICE ────────────────────────────────────────────────
const M10 = 'Performance & Device';
[
    ['Performance', 'App Cold Start Under 3s', 'Fresh launch', 'Launch app measure time', 'App ready in under 3 seconds'],
    ['Performance', 'App Warm Start Under 1.5s', 'App in background', 'Resume app measure time', 'Ready in under 1.5 seconds'],
    ['Performance', 'Inventory Scroll 60fps', '100+ items in inventory', 'Scroll fast', 'No frame drops observed'],
    ['Performance', 'Image Load Performance', 'Item with photo', 'Navigate to item detail', 'Photo loads under 1 second'],
    ['Performance', 'Network Request Timeout Handling', 'Slow network', 'Perform any action', 'Timeout message shown gracefully'],
    ['Performance', 'Memory Usage Under 200MB', 'App running 10 min', 'Check device memory', 'Memory under 200MB'],
    ['Performance', 'No ANR During Heavy Operations', 'Many items', 'Perform bulk edit', 'No ANR dialog appears'],
    ['Performance', 'Battery Usage Acceptable', 'Use app 1 hour', 'Check battery stats', 'App not in battery drain list'],
    ['Performance', 'Search Debounce Works', 'In search mode', 'Type quickly', 'API called once per pause not each key'],
    ['Performance', 'Lazy Loading for Images', 'Image-heavy list', 'Scroll list', 'Images load as they enter view'],
    ['Offline', 'App Usable Offline', 'No network', 'Open app navigate', 'Core screens accessible'],
    ['Offline', 'Offline Indicator Shown', 'No network', 'View top bar', 'Offline badge banner present'],
    ['Offline', 'Offline Writes Sync on Reconnect', 'Created items offline', 'Reconnect to internet', 'Offline items synced to server'],
    ['Offline', 'Conflict on Sync Resolved', 'Offline edit and online edit same item', 'Reconnect', 'Conflict dialog shown'],
    ['Offline', 'Read-Only Mode on Offline', 'No network', 'Try to add item', 'Queued for sync toast shown'],
    ['Compatibility', 'Runs on Android 10', 'Android 10 device', 'Launch and navigate', 'All features work'],
    ['Compatibility', 'Runs on Android 13', 'Android 13 device', 'Launch and navigate', 'All features work'],
    ['Compatibility', 'Runs on iOS 15', 'iOS 15 device', 'Launch and navigate', 'All features work'],
    ['Compatibility', 'Runs on iOS 17', 'iOS 17 device', 'Launch and navigate', 'All features work'],
    ['Compatibility', 'Small Screen 5 Inch', 'Small device', 'Launch app', 'No UI overlap or cutoff'],
    ['Compatibility', 'Large Screen 6.7 Inch', 'Large device', 'Launch app', 'Layout uses space well'],
    ['Compatibility', 'Tablet Layout', 'Tablet device', 'Launch app', 'Two-panel layout shown'],
    ['Compatibility', 'Notch Display Support', 'Notched device', 'Launch app', 'Content not hidden behind notch'],
    ['Compatibility', 'Dynamic Island Support iOS', 'iPhone 14 Pro', 'View top bar', 'Notifications compatible with Dynamic Island'],
    ['Compatibility', 'Foldable Device Support', 'Foldable phone', 'Launch folded unfold', 'Layout adapts to screen change'],
    ['Gestures', 'Swipe to Delete in List', 'Item in list', 'Swipe item left', 'Delete option revealed'],
    ['Gestures', 'Pull to Refresh', 'Any list screen', 'Pull down', 'Spinner shown data refreshed'],
    ['Gestures', 'Pinch to Zoom on Images', 'Item photo shown', 'Pinch on photo', 'Photo zooms in out'],
    ['Gestures', 'Long Press for Context Menu', 'Item in list', 'Long press item', 'Context menu shown'],
    ['Gestures', 'Double Tap to Favorite Recipe', 'Recipe card', 'Double tap', 'Recipe saved to favourites'],
    ['Gestures', 'Swipe Between Tabs', 'On any main tab', 'Swipe horizontally', 'Moves to adjacent tab'],
    ['Gestures', 'Back Gesture Android', 'On any sub-screen', 'Swipe from left edge', 'Navigates back'],
    ['Gestures', 'Back Gesture iOS', 'On any sub-screen', 'Swipe from left edge', 'Navigates back'],
    ['Hardware', 'Camera Permission Graceful', 'Camera needed', 'Deny camera', 'Error with settings link shown'],
    ['Hardware', 'Microphone Permission', 'Voice search used', 'Deny microphone', 'Error with settings link shown'],
    ['Hardware', 'GPS Location Permission', 'Store locator used', 'Allow deny location', 'Handled gracefully'],
    ['Hardware', 'Haptic Feedback on Actions', 'Haptics enabled', 'Tap save delete', 'Device vibrates proportionally'],
    ['Hardware', 'Background App Refresh', 'Background refresh on', 'Background app 1 min', 'Data updated when foregrounded'],
    ['Hardware', 'Airplane Mode Handling', 'Airplane mode on', 'Open app', 'Offline mode activates'],
    ['Hardware', 'Low Storage Device', 'Device storage <100MB', 'Launch app', 'Warning shown app functions'],
    ['Crash & Error', 'No Crash on Low Memory', 'Device memory full', 'Launch app', 'App shows error does not crash'],
    ['Crash & Error', 'Error Boundary on Component Crash', 'Force component error', 'Trigger crash', 'Error screen shown not blank'],
    ['Crash & Error', 'API Error Handled Gracefully', 'Server returns 500', 'Perform action', 'User-friendly error message shown'],
    ['Crash & Error', 'No Crash on Rapid Navigation', 'App running', 'Rapidly tap between screens', 'No crash or freeze'],
    ['Crash & Error', 'App Recovers from Crash', 'App crashed', 'Relaunch app', 'App opens cleanly to last state'],
    ['Crash & Error', 'Analytics Crash Reported', 'Crash monitoring on', 'Trigger crash', 'Crash logged in analytics dashboard'],
    ['Accessibility', 'Font Size Accessibility', 'Large font device setting', 'Open app', 'Text does not overflow cards'],
    ['Accessibility', 'Color Contrast Compliance', 'Any screen', 'View UI elements', 'Elements meet WCAG AA contrast'],
    ['Accessibility', 'Screen Reader Navigation Order', 'TalkBack active', 'Navigate screen', 'Focus order is logical'],
    ['Accessibility', 'Touch Target Size Minimum 44pt', 'Any screen', 'View all buttons', 'All targets >= 44x44 points'],
    ['Accessibility', 'Reduce Motion Compliance', 'Reduce motion on', 'Open app', 'Animations minimized'],
].forEach(([sub, title, pre, steps, exp]) => rows.push(tc(M10, sub, title, pre, steps, exp)));

// ── Write CSV ────────────────────────────────────────────────────────────────
function escapeCSV(v) {
    const s = String(v);
    return (s.includes(',') || s.includes('"') || s.includes('\n'))
        ? `"${s.replace(/"/g, '""')}"` : s;
}

const lines = [
    HEADERS.map(escapeCSV).join(','),
    ...rows.map(r => r.map(escapeCSV).join(','))
];

fs.writeFileSync(OUTPUT_FILE, '\uFEFF' + lines.join('\r\n'), 'utf8');
console.log(`✅ Generated ${rows.length} test cases → ${OUTPUT_FILE}`);
